// Copyright 2026 Idyl Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: idyl/delivery/v2/delivery.proto

// This file defines the two prefaces with which an edge opens a delivery
// stream to a dock: EventPush on a unidirectional stream and RpcOpen on a
// bidirectional stream. Each is written as one frame: a 4-byte big-endian
// length followed by the marshaled message.
//
// These messages carry no identity. The dock knows its own identity from its
// SVID, and the fabric authorizes every delivery before the edge opens the
// stream; there is no field in which either party could assert an identity.
//
// Lane streams on the same connection do not use these prefaces. A lane
// stream begins with the raw lane stream header, whose first byte is the
// lane stream kind (0x03). A delivery frame's first byte is always 0x00,
// because the 1 MiB frame size limit keeps the high byte of the length zero.
// A dock therefore tells rpc streams and lane streams apart by their first
// byte.

package deliveryv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventPush carries one delivered payload to the dock on a unidirectional
// stream the edge opens. Each event has its own stream, which gives every
// event independent flow control with no head-of-line blocking between
// events. The edge closes the stream after this one frame.
type EventPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventPush) Reset() {
	*x = EventPush{}
	mi := &file_idyl_delivery_v2_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPush) ProtoMessage() {}

func (x *EventPush) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_delivery_v2_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPush.ProtoReflect.Descriptor instead.
func (*EventPush) Descriptor() ([]byte, []int) {
	return file_idyl_delivery_v2_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *EventPush) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// RpcOpen is the first frame on a bidirectional stream the edge opens to the
// dock. After it, the stream is the rpc's byte pipe in both directions.
// metadata comes from the party that opened the rpc and is opaque to the
// fabric.
type RpcOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      []byte                 `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcOpen) Reset() {
	*x = RpcOpen{}
	mi := &file_idyl_delivery_v2_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcOpen) ProtoMessage() {}

func (x *RpcOpen) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_delivery_v2_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcOpen.ProtoReflect.Descriptor instead.
func (*RpcOpen) Descriptor() ([]byte, []int) {
	return file_idyl_delivery_v2_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *RpcOpen) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_idyl_delivery_v2_delivery_proto protoreflect.FileDescriptor

const file_idyl_delivery_v2_delivery_proto_rawDesc = "" +
	"\n" +
	"\x1fidyl/delivery/v2/delivery.proto\x12\x10idyl.delivery.v2\"%\n" +
	"\tEventPush\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"%\n" +
	"\aRpcOpen\x12\x1a\n" +
	"\bmetadata\x18\x01 \x01(\fR\bmetadataB4Z2github.com/idyl-labs/hyperplane-go/wire/deliveryv2b\x06proto3"

var (
	file_idyl_delivery_v2_delivery_proto_rawDescOnce sync.Once
	file_idyl_delivery_v2_delivery_proto_rawDescData []byte
)

func file_idyl_delivery_v2_delivery_proto_rawDescGZIP() []byte {
	file_idyl_delivery_v2_delivery_proto_rawDescOnce.Do(func() {
		file_idyl_delivery_v2_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idyl_delivery_v2_delivery_proto_rawDesc), len(file_idyl_delivery_v2_delivery_proto_rawDesc)))
	})
	return file_idyl_delivery_v2_delivery_proto_rawDescData
}

var file_idyl_delivery_v2_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_idyl_delivery_v2_delivery_proto_goTypes = []any{
	(*EventPush)(nil), // 0: idyl.delivery.v2.EventPush
	(*RpcOpen)(nil),   // 1: idyl.delivery.v2.RpcOpen
}
var file_idyl_delivery_v2_delivery_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idyl_delivery_v2_delivery_proto_init() }
func file_idyl_delivery_v2_delivery_proto_init() {
	if File_idyl_delivery_v2_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idyl_delivery_v2_delivery_proto_rawDesc), len(file_idyl_delivery_v2_delivery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idyl_delivery_v2_delivery_proto_goTypes,
		DependencyIndexes: file_idyl_delivery_v2_delivery_proto_depIdxs,
		MessageInfos:      file_idyl_delivery_v2_delivery_proto_msgTypes,
	}.Build()
	File_idyl_delivery_v2_delivery_proto = out.File
	file_idyl_delivery_v2_delivery_proto_goTypes = nil
	file_idyl_delivery_v2_delivery_proto_depIdxs = nil
}
