// Copyright 2026 Idyl Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: idyl/common/v2/common.proto

// This file defines the identifier types and enums shared by the Hyperplane
// wire contracts: the edge and dock generation identifiers (EdgeTag,
// DockGen) and the endpoint and session classification enums. The dock,
// admission and minting contracts import them.
//
// Evolution is additive: decoders must ignore unknown fields, and encoders
// must never change the meaning or type of an existing field number.

package commonv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EndpointKind is the kind of principal at a dock, derived from the path
// shape of its SPIFFE ID.
//
// Kinds are additive. A consumer must refuse a dock whose endpoint kind it
// does not know, because the rules that apply to an endpoint cannot be
// guessed from an unknown kind.
type EndpointKind int32

const (
	EndpointKind_ENDPOINT_KIND_UNSPECIFIED EndpointKind = 0
	// A Node: one machine running the node daemon.
	EndpointKind_ENDPOINT_KIND_NODE EndpointKind = 1
	// A Pod: one workload instance placed on a Node.
	EndpointKind_ENDPOINT_KIND_POD EndpointKind = 2
	// One leg of an interactive workload session; see SessionKind and
	// SessionLeg.
	EndpointKind_ENDPOINT_KIND_SESSION EndpointKind = 3
	// A component of the fabric itself.
	EndpointKind_ENDPOINT_KIND_FABRIC EndpointKind = 4
	// A share: a tunnel dock that serves as a data-plane lane target, follows
	// session rules, and is bound to no Node.
	EndpointKind_ENDPOINT_KIND_SHARE EndpointKind = 5
)

// Enum value maps for EndpointKind.
var (
	EndpointKind_name = map[int32]string{
		0: "ENDPOINT_KIND_UNSPECIFIED",
		1: "ENDPOINT_KIND_NODE",
		2: "ENDPOINT_KIND_POD",
		3: "ENDPOINT_KIND_SESSION",
		4: "ENDPOINT_KIND_FABRIC",
		5: "ENDPOINT_KIND_SHARE",
	}
	EndpointKind_value = map[string]int32{
		"ENDPOINT_KIND_UNSPECIFIED": 0,
		"ENDPOINT_KIND_NODE":        1,
		"ENDPOINT_KIND_POD":         2,
		"ENDPOINT_KIND_SESSION":     3,
		"ENDPOINT_KIND_FABRIC":      4,
		"ENDPOINT_KIND_SHARE":       5,
	}
)

func (x EndpointKind) Enum() *EndpointKind {
	p := new(EndpointKind)
	*p = x
	return p
}

func (x EndpointKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointKind) Descriptor() protoreflect.EnumDescriptor {
	return file_idyl_common_v2_common_proto_enumTypes[0].Descriptor()
}

func (EndpointKind) Type() protoreflect.EnumType {
	return &file_idyl_common_v2_common_proto_enumTypes[0]
}

func (x EndpointKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointKind.Descriptor instead.
func (EndpointKind) EnumDescriptor() ([]byte, []int) {
	return file_idyl_common_v2_common_proto_rawDescGZIP(), []int{0}
}

// SessionKind classifies a session principal. It applies only to the session
// endpoint kind. New kinds are additive enum values.
type SessionKind int32

const (
	SessionKind_SESSION_KIND_UNSPECIFIED SessionKind = 0
	SessionKind_SESSION_KIND_EXEC        SessionKind = 1
	SessionKind_SESSION_KIND_LOGS        SessionKind = 2
	SessionKind_SESSION_KIND_SHELL       SessionKind = 3
)

// Enum value maps for SessionKind.
var (
	SessionKind_name = map[int32]string{
		0: "SESSION_KIND_UNSPECIFIED",
		1: "SESSION_KIND_EXEC",
		2: "SESSION_KIND_LOGS",
		3: "SESSION_KIND_SHELL",
	}
	SessionKind_value = map[string]int32{
		"SESSION_KIND_UNSPECIFIED": 0,
		"SESSION_KIND_EXEC":        1,
		"SESSION_KIND_LOGS":        2,
		"SESSION_KIND_SHELL":       3,
	}
)

func (x SessionKind) Enum() *SessionKind {
	p := new(SessionKind)
	*p = x
	return p
}

func (x SessionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_idyl_common_v2_common_proto_enumTypes[1].Descriptor()
}

func (SessionKind) Type() protoreflect.EnumType {
	return &file_idyl_common_v2_common_proto_enumTypes[1]
}

func (x SessionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionKind.Descriptor instead.
func (SessionKind) EnumDescriptor() ([]byte, []int) {
	return file_idyl_common_v2_common_proto_rawDescGZIP(), []int{1}
}

// SessionLeg distinguishes the two endpoint certificates that take part in
// one workload session splice. A workload session is identified by the pair
// (session_id, session_leg), not by session_id alone.
type SessionLeg int32

const (
	SessionLeg_SESSION_LEG_UNSPECIFIED SessionLeg = 0
	SessionLeg_SESSION_LEG_CLIENT      SessionLeg = 1
	SessionLeg_SESSION_LEG_PROXY       SessionLeg = 2
)

// Enum value maps for SessionLeg.
var (
	SessionLeg_name = map[int32]string{
		0: "SESSION_LEG_UNSPECIFIED",
		1: "SESSION_LEG_CLIENT",
		2: "SESSION_LEG_PROXY",
	}
	SessionLeg_value = map[string]int32{
		"SESSION_LEG_UNSPECIFIED": 0,
		"SESSION_LEG_CLIENT":      1,
		"SESSION_LEG_PROXY":       2,
	}
)

func (x SessionLeg) Enum() *SessionLeg {
	p := new(SessionLeg)
	*p = x
	return p
}

func (x SessionLeg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionLeg) Descriptor() protoreflect.EnumDescriptor {
	return file_idyl_common_v2_common_proto_enumTypes[2].Descriptor()
}

func (SessionLeg) Type() protoreflect.EnumType {
	return &file_idyl_common_v2_common_proto_enumTypes[2]
}

func (x SessionLeg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionLeg.Descriptor instead.
func (SessionLeg) EnumDescriptor() ([]byte, []int) {
	return file_idyl_common_v2_common_proto_rawDescGZIP(), []int{2}
}

// EdgeTag identifies one edge process incarnation serving under one lease.
// When that incarnation ends, every dock it served ends with it.
type EdgeTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incarnation   []byte                 `protobuf:"bytes,1,opt,name=incarnation,proto3" json:"incarnation,omitempty"`        // 16 bytes, random, chosen at process start
	LeaseId       []byte                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"` // at most 16 bytes, opaque, issued with the edge's lease
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeTag) Reset() {
	*x = EdgeTag{}
	mi := &file_idyl_common_v2_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeTag) ProtoMessage() {}

func (x *EdgeTag) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_common_v2_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeTag.ProtoReflect.Descriptor instead.
func (*EdgeTag) Descriptor() ([]byte, []int) {
	return file_idyl_common_v2_common_proto_rawDescGZIP(), []int{0}
}

func (x *EdgeTag) GetIncarnation() []byte {
	if x != nil {
		return x.Incarnation
	}
	return nil
}

func (x *EdgeTag) GetLeaseId() []byte {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

// DockGen identifies one dock generation. State recorded for one generation
// never applies to another.
//
// The nonce is the succession credential: a client that names its previous
// generation, nonce included, makes its next dock a succession. The edge
// discloses it only inside the dock's own TLS connection. It must never
// appear in logs, errors, metrics or any other output; render a generation
// as edge_tag#slot.epoch.
type DockGen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edge          *EdgeTag               `protobuf:"bytes,1,opt,name=edge,proto3" json:"edge,omitempty"`
	Slot          uint32                 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	SlotEpoch     uint32                 `protobuf:"varint,3,opt,name=slot_epoch,json=slotEpoch,proto3" json:"slot_epoch,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"` // 12 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockGen) Reset() {
	*x = DockGen{}
	mi := &file_idyl_common_v2_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockGen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockGen) ProtoMessage() {}

func (x *DockGen) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_common_v2_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockGen.ProtoReflect.Descriptor instead.
func (*DockGen) Descriptor() ([]byte, []int) {
	return file_idyl_common_v2_common_proto_rawDescGZIP(), []int{1}
}

func (x *DockGen) GetEdge() *EdgeTag {
	if x != nil {
		return x.Edge
	}
	return nil
}

func (x *DockGen) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *DockGen) GetSlotEpoch() uint32 {
	if x != nil {
		return x.SlotEpoch
	}
	return 0
}

func (x *DockGen) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

var File_idyl_common_v2_common_proto protoreflect.FileDescriptor

const file_idyl_common_v2_common_proto_rawDesc = "" +
	"\n" +
	"\x1bidyl/common/v2/common.proto\x12\x0eidyl.common.v2\"F\n" +
	"\aEdgeTag\x12 \n" +
	"\vincarnation\x18\x01 \x01(\fR\vincarnation\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\fR\aleaseId\"\x7f\n" +
	"\aDockGen\x12+\n" +
	"\x04edge\x18\x01 \x01(\v2\x17.idyl.common.v2.EdgeTagR\x04edge\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\rR\x04slot\x12\x1d\n" +
	"\n" +
	"slot_epoch\x18\x03 \x01(\rR\tslotEpoch\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce*\xaa\x01\n" +
	"\fEndpointKind\x12\x1d\n" +
	"\x19ENDPOINT_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ENDPOINT_KIND_NODE\x10\x01\x12\x15\n" +
	"\x11ENDPOINT_KIND_POD\x10\x02\x12\x19\n" +
	"\x15ENDPOINT_KIND_SESSION\x10\x03\x12\x18\n" +
	"\x14ENDPOINT_KIND_FABRIC\x10\x04\x12\x17\n" +
	"\x13ENDPOINT_KIND_SHARE\x10\x05*q\n" +
	"\vSessionKind\x12\x1c\n" +
	"\x18SESSION_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SESSION_KIND_EXEC\x10\x01\x12\x15\n" +
	"\x11SESSION_KIND_LOGS\x10\x02\x12\x16\n" +
	"\x12SESSION_KIND_SHELL\x10\x03*X\n" +
	"\n" +
	"SessionLeg\x12\x1b\n" +
	"\x17SESSION_LEG_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SESSION_LEG_CLIENT\x10\x01\x12\x15\n" +
	"\x11SESSION_LEG_PROXY\x10\x02B2Z0github.com/idyl-labs/hyperplane-go/wire/commonv2b\x06proto3"

var (
	file_idyl_common_v2_common_proto_rawDescOnce sync.Once
	file_idyl_common_v2_common_proto_rawDescData []byte
)

func file_idyl_common_v2_common_proto_rawDescGZIP() []byte {
	file_idyl_common_v2_common_proto_rawDescOnce.Do(func() {
		file_idyl_common_v2_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idyl_common_v2_common_proto_rawDesc), len(file_idyl_common_v2_common_proto_rawDesc)))
	})
	return file_idyl_common_v2_common_proto_rawDescData
}

var file_idyl_common_v2_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_idyl_common_v2_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_idyl_common_v2_common_proto_goTypes = []any{
	(EndpointKind)(0), // 0: idyl.common.v2.EndpointKind
	(SessionKind)(0),  // 1: idyl.common.v2.SessionKind
	(SessionLeg)(0),   // 2: idyl.common.v2.SessionLeg
	(*EdgeTag)(nil),   // 3: idyl.common.v2.EdgeTag
	(*DockGen)(nil),   // 4: idyl.common.v2.DockGen
}
var file_idyl_common_v2_common_proto_depIdxs = []int32{
	3, // 0: idyl.common.v2.DockGen.edge:type_name -> idyl.common.v2.EdgeTag
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_idyl_common_v2_common_proto_init() }
func file_idyl_common_v2_common_proto_init() {
	if File_idyl_common_v2_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idyl_common_v2_common_proto_rawDesc), len(file_idyl_common_v2_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idyl_common_v2_common_proto_goTypes,
		DependencyIndexes: file_idyl_common_v2_common_proto_depIdxs,
		EnumInfos:         file_idyl_common_v2_common_proto_enumTypes,
		MessageInfos:      file_idyl_common_v2_common_proto_msgTypes,
	}.Build()
	File_idyl_common_v2_common_proto = out.File
	file_idyl_common_v2_common_proto_goTypes = nil
	file_idyl_common_v2_common_proto_depIdxs = nil
}
