// Copyright 2026 Idyl Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: idyl/common/v2/plane.proto

// This file defines Plane, the fabric plane an endpoint is admitted to.

package commonv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Plane identifies a fabric plane. A zone runs a control plane and a data
// plane as separate fabric instances. An admission lease names exactly one
// plane and binds only to a connection made on that plane.
type Plane int32

const (
	Plane_PLANE_UNSPECIFIED Plane = 0
	Plane_PLANE_CONTROL     Plane = 1
	Plane_PLANE_DATA        Plane = 2
)

// Enum value maps for Plane.
var (
	Plane_name = map[int32]string{
		0: "PLANE_UNSPECIFIED",
		1: "PLANE_CONTROL",
		2: "PLANE_DATA",
	}
	Plane_value = map[string]int32{
		"PLANE_UNSPECIFIED": 0,
		"PLANE_CONTROL":     1,
		"PLANE_DATA":        2,
	}
)

func (x Plane) Enum() *Plane {
	p := new(Plane)
	*p = x
	return p
}

func (x Plane) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Plane) Descriptor() protoreflect.EnumDescriptor {
	return file_idyl_common_v2_plane_proto_enumTypes[0].Descriptor()
}

func (Plane) Type() protoreflect.EnumType {
	return &file_idyl_common_v2_plane_proto_enumTypes[0]
}

func (x Plane) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Plane.Descriptor instead.
func (Plane) EnumDescriptor() ([]byte, []int) {
	return file_idyl_common_v2_plane_proto_rawDescGZIP(), []int{0}
}

var File_idyl_common_v2_plane_proto protoreflect.FileDescriptor

const file_idyl_common_v2_plane_proto_rawDesc = "" +
	"\n" +
	"\x1aidyl/common/v2/plane.proto\x12\x0eidyl.common.v2*A\n" +
	"\x05Plane\x12\x15\n" +
	"\x11PLANE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPLANE_CONTROL\x10\x01\x12\x0e\n" +
	"\n" +
	"PLANE_DATA\x10\x02B2Z0github.com/idyl-labs/hyperplane-go/wire/commonv2b\x06proto3"

var (
	file_idyl_common_v2_plane_proto_rawDescOnce sync.Once
	file_idyl_common_v2_plane_proto_rawDescData []byte
)

func file_idyl_common_v2_plane_proto_rawDescGZIP() []byte {
	file_idyl_common_v2_plane_proto_rawDescOnce.Do(func() {
		file_idyl_common_v2_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idyl_common_v2_plane_proto_rawDesc), len(file_idyl_common_v2_plane_proto_rawDesc)))
	})
	return file_idyl_common_v2_plane_proto_rawDescData
}

var file_idyl_common_v2_plane_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_idyl_common_v2_plane_proto_goTypes = []any{
	(Plane)(0), // 0: idyl.common.v2.Plane
}
var file_idyl_common_v2_plane_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idyl_common_v2_plane_proto_init() }
func file_idyl_common_v2_plane_proto_init() {
	if File_idyl_common_v2_plane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idyl_common_v2_plane_proto_rawDesc), len(file_idyl_common_v2_plane_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idyl_common_v2_plane_proto_goTypes,
		DependencyIndexes: file_idyl_common_v2_plane_proto_depIdxs,
		EnumInfos:         file_idyl_common_v2_plane_proto_enumTypes,
	}.Build()
	File_idyl_common_v2_plane_proto = out.File
	file_idyl_common_v2_plane_proto_goTypes = nil
	file_idyl_common_v2_plane_proto_depIdxs = nil
}
