// Copyright 2026 Idyl Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: idyl/dock/v3/dock.proto

// This file defines dock/3, the dock control channel for dynamically
// admitted principals (Nodes, Pods, sessions and shares). dock/3 is dock/2
// with demand-admission material in DockHello: the exact admission lease
// envelope, the exact canonical dock proof input bound to this TLS
// connection, and an Ed25519 signature over that input made with the SVID
// key. The material is mandatory in a dock/3 DockHello. Every other control
// frame, field number and meaning is identical to idyl.dock.v2; see that
// package for the semantics of each frame.

package dockv3

import (
	commonv2 "github.com/idyl-labs/hyperplane-go/wire/commonv2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LaneCloseCause classifies why a lane ended. Its values and meanings are
// those of idyl.dock.v2.LaneCloseCause.
type LaneCloseCause int32

const (
	LaneCloseCause_LANE_CLOSE_CAUSE_UNSPECIFIED    LaneCloseCause = 0
	LaneCloseCause_LANE_CLOSE_CAUSE_LEG_UNDOCK     LaneCloseCause = 1
	LaneCloseCause_LANE_CLOSE_CAUSE_SUBTREE_DEATH  LaneCloseCause = 2
	LaneCloseCause_LANE_CLOSE_CAUSE_EPOCH_RETIRED  LaneCloseCause = 3
	LaneCloseCause_LANE_CLOSE_CAUSE_GEN_MISMATCH   LaneCloseCause = 4
	LaneCloseCause_LANE_CLOSE_CAUSE_POLICY_REVOKED LaneCloseCause = 5
	LaneCloseCause_LANE_CLOSE_CAUSE_EXPIRY         LaneCloseCause = 6
	LaneCloseCause_LANE_CLOSE_CAUSE_DRAINED        LaneCloseCause = 7
)

// Enum value maps for LaneCloseCause.
var (
	LaneCloseCause_name = map[int32]string{
		0: "LANE_CLOSE_CAUSE_UNSPECIFIED",
		1: "LANE_CLOSE_CAUSE_LEG_UNDOCK",
		2: "LANE_CLOSE_CAUSE_SUBTREE_DEATH",
		3: "LANE_CLOSE_CAUSE_EPOCH_RETIRED",
		4: "LANE_CLOSE_CAUSE_GEN_MISMATCH",
		5: "LANE_CLOSE_CAUSE_POLICY_REVOKED",
		6: "LANE_CLOSE_CAUSE_EXPIRY",
		7: "LANE_CLOSE_CAUSE_DRAINED",
	}
	LaneCloseCause_value = map[string]int32{
		"LANE_CLOSE_CAUSE_UNSPECIFIED":    0,
		"LANE_CLOSE_CAUSE_LEG_UNDOCK":     1,
		"LANE_CLOSE_CAUSE_SUBTREE_DEATH":  2,
		"LANE_CLOSE_CAUSE_EPOCH_RETIRED":  3,
		"LANE_CLOSE_CAUSE_GEN_MISMATCH":   4,
		"LANE_CLOSE_CAUSE_POLICY_REVOKED": 5,
		"LANE_CLOSE_CAUSE_EXPIRY":         6,
		"LANE_CLOSE_CAUSE_DRAINED":        7,
	}
)

func (x LaneCloseCause) Enum() *LaneCloseCause {
	p := new(LaneCloseCause)
	*p = x
	return p
}

func (x LaneCloseCause) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LaneCloseCause) Descriptor() protoreflect.EnumDescriptor {
	return file_idyl_dock_v3_dock_proto_enumTypes[0].Descriptor()
}

func (LaneCloseCause) Type() protoreflect.EnumType {
	return &file_idyl_dock_v3_dock_proto_enumTypes[0]
}

func (x LaneCloseCause) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LaneCloseCause.Descriptor instead.
func (LaneCloseCause) EnumDescriptor() ([]byte, []int) {
	return file_idyl_dock_v3_dock_proto_rawDescGZIP(), []int{0}
}

// DockHello is the client's opening frame on the control stream. Fields 1 to
// 3 mean what they mean in dock/2. The proof input repeats the contract,
// keepalive_ms, predecessor_gen and a SHA-256 digest of lease_envelope, and
// a verifier refuses a hello whose fields differ from the proof input.
type DockHello struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Contract           string                 `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"` // "dock/3"
	KeepaliveMs        uint32                 `protobuf:"varint,2,opt,name=keepalive_ms,json=keepaliveMs,proto3" json:"keepalive_ms,omitempty"`
	PredecessorGen     *commonv2.DockGen      `protobuf:"bytes,3,opt,name=predecessor_gen,json=predecessorGen,proto3" json:"predecessor_gen,omitempty"`
	LeaseEnvelope      []byte                 `protobuf:"bytes,4,opt,name=lease_envelope,json=leaseEnvelope,proto3" json:"lease_envelope,omitempty"`                  // exact canonical ZoneAdmissionLease bytes
	DockProofInput     []byte                 `protobuf:"bytes,5,opt,name=dock_proof_input,json=dockProofInput,proto3" json:"dock_proof_input,omitempty"`             // exact canonical DockProofInput bytes
	DockProofSignature []byte                 `protobuf:"bytes,6,opt,name=dock_proof_signature,json=dockProofSignature,proto3" json:"dock_proof_signature,omitempty"` // Ed25519 SVID-key signature over the domain-separated proof input
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DockHello) Reset() {
	*x = DockHello{}
	mi := &file_idyl_dock_v3_dock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockHello) ProtoMessage() {}

func (x *DockHello) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_dock_v3_dock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockHello.ProtoReflect.Descriptor instead.
func (*DockHello) Descriptor() ([]byte, []int) {
	return file_idyl_dock_v3_dock_proto_rawDescGZIP(), []int{0}
}

func (x *DockHello) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *DockHello) GetKeepaliveMs() uint32 {
	if x != nil {
		return x.KeepaliveMs
	}
	return 0
}

func (x *DockHello) GetPredecessorGen() *commonv2.DockGen {
	if x != nil {
		return x.PredecessorGen
	}
	return nil
}

func (x *DockHello) GetLeaseEnvelope() []byte {
	if x != nil {
		return x.LeaseEnvelope
	}
	return nil
}

func (x *DockHello) GetDockProofInput() []byte {
	if x != nil {
		return x.DockProofInput
	}
	return nil
}

func (x *DockHello) GetDockProofSignature() []byte {
	if x != nil {
		return x.DockProofSignature
	}
	return nil
}

// DockWelcome is the edge's reply, as in dock/2.
type DockWelcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gen           *commonv2.DockGen      `protobuf:"bytes,1,opt,name=gen,proto3" json:"gen,omitempty"`
	KeepaliveMs   uint32                 `protobuf:"varint,2,opt,name=keepalive_ms,json=keepaliveMs,proto3" json:"keepalive_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockWelcome) Reset() {
	*x = DockWelcome{}
	mi := &file_idyl_dock_v3_dock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockWelcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockWelcome) ProtoMessage() {}

func (x *DockWelcome) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_dock_v3_dock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockWelcome.ProtoReflect.Descriptor instead.
func (*DockWelcome) Descriptor() ([]byte, []int) {
	return file_idyl_dock_v3_dock_proto_rawDescGZIP(), []int{1}
}

func (x *DockWelcome) GetGen() *commonv2.DockGen {
	if x != nil {
		return x.Gen
	}
	return nil
}

func (x *DockWelcome) GetKeepaliveMs() uint32 {
	if x != nil {
		return x.KeepaliveMs
	}
	return 0
}

// DockDrain is the edge's drain signal, as in dock/2.
type DockDrain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	DeadlineUnix  uint64                 `protobuf:"varint,2,opt,name=deadline_unix,json=deadlineUnix,proto3" json:"deadline_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockDrain) Reset() {
	*x = DockDrain{}
	mi := &file_idyl_dock_v3_dock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockDrain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockDrain) ProtoMessage() {}

func (x *DockDrain) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_dock_v3_dock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockDrain.ProtoReflect.Descriptor instead.
func (*DockDrain) Descriptor() ([]byte, []int) {
	return file_idyl_dock_v3_dock_proto_rawDescGZIP(), []int{2}
}

func (x *DockDrain) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DockDrain) GetDeadlineUnix() uint64 {
	if x != nil {
		return x.DeadlineUnix
	}
	return 0
}

// DockOverloaded is the edge's overload refusal, as in dock/2.
type DockOverloaded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetryAfterMs  uint32                 `protobuf:"varint,1,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockOverloaded) Reset() {
	*x = DockOverloaded{}
	mi := &file_idyl_dock_v3_dock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockOverloaded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockOverloaded) ProtoMessage() {}

func (x *DockOverloaded) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_dock_v3_dock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockOverloaded.ProtoReflect.Descriptor instead.
func (*DockOverloaded) Descriptor() ([]byte, []int) {
	return file_idyl_dock_v3_dock_proto_rawDescGZIP(), []int{3}
}

func (x *DockOverloaded) GetRetryAfterMs() uint32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

// LaneAttached tells a dock that a lane was installed on its connection, as
// in dock/2. lane_class uses the same bits: 2 stream, 3 flow, 4 ingress
// target, 5 splice leg.
type LaneAttached struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LaneId        uint64                 `protobuf:"varint,1,opt,name=lane_id,json=laneId,proto3" json:"lane_id,omitempty"`
	PeerPrincipal string                 `protobuf:"bytes,2,opt,name=peer_principal,json=peerPrincipal,proto3" json:"peer_principal,omitempty"` // advisory only
	LaneClass     uint64                 `protobuf:"varint,3,opt,name=lane_class,json=laneClass,proto3" json:"lane_class,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaneAttached) Reset() {
	*x = LaneAttached{}
	mi := &file_idyl_dock_v3_dock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaneAttached) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaneAttached) ProtoMessage() {}

func (x *LaneAttached) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_dock_v3_dock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaneAttached.ProtoReflect.Descriptor instead.
func (*LaneAttached) Descriptor() ([]byte, []int) {
	return file_idyl_dock_v3_dock_proto_rawDescGZIP(), []int{4}
}

func (x *LaneAttached) GetLaneId() uint64 {
	if x != nil {
		return x.LaneId
	}
	return 0
}

func (x *LaneAttached) GetPeerPrincipal() string {
	if x != nil {
		return x.PeerPrincipal
	}
	return ""
}

func (x *LaneAttached) GetLaneClass() uint64 {
	if x != nil {
		return x.LaneClass
	}
	return 0
}

func (x *LaneAttached) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// LaneClosed tells a dock that a lane ended, as in dock/2.
type LaneClosed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LaneId        uint64                 `protobuf:"varint,1,opt,name=lane_id,json=laneId,proto3" json:"lane_id,omitempty"`
	Cause         LaneCloseCause         `protobuf:"varint,2,opt,name=cause,proto3,enum=idyl.dock.v3.LaneCloseCause" json:"cause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaneClosed) Reset() {
	*x = LaneClosed{}
	mi := &file_idyl_dock_v3_dock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaneClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaneClosed) ProtoMessage() {}

func (x *LaneClosed) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_dock_v3_dock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaneClosed.ProtoReflect.Descriptor instead.
func (*LaneClosed) Descriptor() ([]byte, []int) {
	return file_idyl_dock_v3_dock_proto_rawDescGZIP(), []int{5}
}

func (x *LaneClosed) GetLaneId() uint64 {
	if x != nil {
		return x.LaneId
	}
	return 0
}

func (x *LaneClosed) GetCause() LaneCloseCause {
	if x != nil {
		return x.Cause
	}
	return LaneCloseCause_LANE_CLOSE_CAUSE_UNSPECIFIED
}

// ClientToEdge frames the client-to-edge direction of the control stream.
type ClientToEdge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClientToEdge_Hello
	Msg           isClientToEdge_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientToEdge) Reset() {
	*x = ClientToEdge{}
	mi := &file_idyl_dock_v3_dock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientToEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToEdge) ProtoMessage() {}

func (x *ClientToEdge) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_dock_v3_dock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToEdge.ProtoReflect.Descriptor instead.
func (*ClientToEdge) Descriptor() ([]byte, []int) {
	return file_idyl_dock_v3_dock_proto_rawDescGZIP(), []int{6}
}

func (x *ClientToEdge) GetMsg() isClientToEdge_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientToEdge) GetHello() *DockHello {
	if x != nil {
		if x, ok := x.Msg.(*ClientToEdge_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

type isClientToEdge_Msg interface {
	isClientToEdge_Msg()
}

type ClientToEdge_Hello struct {
	Hello *DockHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

func (*ClientToEdge_Hello) isClientToEdge_Msg() {}

// EdgeToClient frames the edge-to-client direction of the control stream.
type EdgeToClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*EdgeToClient_Welcome
	//	*EdgeToClient_Drain
	//	*EdgeToClient_Overloaded
	//	*EdgeToClient_LaneAttached
	//	*EdgeToClient_LaneClosed
	Msg           isEdgeToClient_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeToClient) Reset() {
	*x = EdgeToClient{}
	mi := &file_idyl_dock_v3_dock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeToClient) ProtoMessage() {}

func (x *EdgeToClient) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_dock_v3_dock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeToClient.ProtoReflect.Descriptor instead.
func (*EdgeToClient) Descriptor() ([]byte, []int) {
	return file_idyl_dock_v3_dock_proto_rawDescGZIP(), []int{7}
}

func (x *EdgeToClient) GetMsg() isEdgeToClient_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *EdgeToClient) GetWelcome() *DockWelcome {
	if x != nil {
		if x, ok := x.Msg.(*EdgeToClient_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *EdgeToClient) GetDrain() *DockDrain {
	if x != nil {
		if x, ok := x.Msg.(*EdgeToClient_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *EdgeToClient) GetOverloaded() *DockOverloaded {
	if x != nil {
		if x, ok := x.Msg.(*EdgeToClient_Overloaded); ok {
			return x.Overloaded
		}
	}
	return nil
}

func (x *EdgeToClient) GetLaneAttached() *LaneAttached {
	if x != nil {
		if x, ok := x.Msg.(*EdgeToClient_LaneAttached); ok {
			return x.LaneAttached
		}
	}
	return nil
}

func (x *EdgeToClient) GetLaneClosed() *LaneClosed {
	if x != nil {
		if x, ok := x.Msg.(*EdgeToClient_LaneClosed); ok {
			return x.LaneClosed
		}
	}
	return nil
}

type isEdgeToClient_Msg interface {
	isEdgeToClient_Msg()
}

type EdgeToClient_Welcome struct {
	Welcome *DockWelcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type EdgeToClient_Drain struct {
	Drain *DockDrain `protobuf:"bytes,2,opt,name=drain,proto3,oneof"`
}

type EdgeToClient_Overloaded struct {
	Overloaded *DockOverloaded `protobuf:"bytes,3,opt,name=overloaded,proto3,oneof"`
}

type EdgeToClient_LaneAttached struct {
	LaneAttached *LaneAttached `protobuf:"bytes,4,opt,name=lane_attached,json=laneAttached,proto3,oneof"`
}

type EdgeToClient_LaneClosed struct {
	LaneClosed *LaneClosed `protobuf:"bytes,5,opt,name=lane_closed,json=laneClosed,proto3,oneof"`
}

func (*EdgeToClient_Welcome) isEdgeToClient_Msg() {}

func (*EdgeToClient_Drain) isEdgeToClient_Msg() {}

func (*EdgeToClient_Overloaded) isEdgeToClient_Msg() {}

func (*EdgeToClient_LaneAttached) isEdgeToClient_Msg() {}

func (*EdgeToClient_LaneClosed) isEdgeToClient_Msg() {}

var File_idyl_dock_v3_dock_proto protoreflect.FileDescriptor

const file_idyl_dock_v3_dock_proto_rawDesc = "" +
	"\n" +
	"\x17idyl/dock/v3/dock.proto\x12\fidyl.dock.v3\x1a\x1fidyl/membership/v2/common.proto\"\x93\x02\n" +
	"\tDockHello\x12\x1a\n" +
	"\bcontract\x18\x01 \x01(\tR\bcontract\x12!\n" +
	"\fkeepalive_ms\x18\x02 \x01(\rR\vkeepaliveMs\x12D\n" +
	"\x0fpredecessor_gen\x18\x03 \x01(\v2\x1b.idyl.membership.v2.DockGenR\x0epredecessorGen\x12%\n" +
	"\x0elease_envelope\x18\x04 \x01(\fR\rleaseEnvelope\x12(\n" +
	"\x10dock_proof_input\x18\x05 \x01(\fR\x0edockProofInput\x120\n" +
	"\x14dock_proof_signature\x18\x06 \x01(\fR\x12dockProofSignature\"_\n" +
	"\vDockWelcome\x12-\n" +
	"\x03gen\x18\x01 \x01(\v2\x1b.idyl.membership.v2.DockGenR\x03gen\x12!\n" +
	"\fkeepalive_ms\x18\x02 \x01(\rR\vkeepaliveMs\"H\n" +
	"\tDockDrain\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12#\n" +
	"\rdeadline_unix\x18\x02 \x01(\x04R\fdeadlineUnix\"6\n" +
	"\x0eDockOverloaded\x12$\n" +
	"\x0eretry_after_ms\x18\x01 \x01(\rR\fretryAfterMs\"\x89\x01\n" +
	"\fLaneAttached\x12\x17\n" +
	"\alane_id\x18\x01 \x01(\x04R\x06laneId\x12%\n" +
	"\x0epeer_principal\x18\x02 \x01(\tR\rpeerPrincipal\x12\x1d\n" +
	"\n" +
	"lane_class\x18\x03 \x01(\x04R\tlaneClass\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\fR\bmetadata\"Y\n" +
	"\n" +
	"LaneClosed\x12\x17\n" +
	"\alane_id\x18\x01 \x01(\x04R\x06laneId\x122\n" +
	"\x05cause\x18\x02 \x01(\x0e2\x1c.idyl.dock.v3.LaneCloseCauseR\x05cause\"F\n" +
	"\fClientToEdge\x12/\n" +
	"\x05hello\x18\x01 \x01(\v2\x17.idyl.dock.v3.DockHelloH\x00R\x05helloB\x05\n" +
	"\x03msg\"\xbd\x02\n" +
	"\fEdgeToClient\x125\n" +
	"\awelcome\x18\x01 \x01(\v2\x19.idyl.dock.v3.DockWelcomeH\x00R\awelcome\x12/\n" +
	"\x05drain\x18\x02 \x01(\v2\x17.idyl.dock.v3.DockDrainH\x00R\x05drain\x12>\n" +
	"\n" +
	"overloaded\x18\x03 \x01(\v2\x1c.idyl.dock.v3.DockOverloadedH\x00R\n" +
	"overloaded\x12A\n" +
	"\rlane_attached\x18\x04 \x01(\v2\x1a.idyl.dock.v3.LaneAttachedH\x00R\flaneAttached\x12;\n" +
	"\vlane_closed\x18\x05 \x01(\v2\x18.idyl.dock.v3.LaneClosedH\x00R\n" +
	"laneClosedB\x05\n" +
	"\x03msg*\x9e\x02\n" +
	"\x0eLaneCloseCause\x12 \n" +
	"\x1cLANE_CLOSE_CAUSE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bLANE_CLOSE_CAUSE_LEG_UNDOCK\x10\x01\x12\"\n" +
	"\x1eLANE_CLOSE_CAUSE_SUBTREE_DEATH\x10\x02\x12\"\n" +
	"\x1eLANE_CLOSE_CAUSE_EPOCH_RETIRED\x10\x03\x12!\n" +
	"\x1dLANE_CLOSE_CAUSE_GEN_MISMATCH\x10\x04\x12#\n" +
	"\x1fLANE_CLOSE_CAUSE_POLICY_REVOKED\x10\x05\x12\x1b\n" +
	"\x17LANE_CLOSE_CAUSE_EXPIRY\x10\x06\x12\x1c\n" +
	"\x18LANE_CLOSE_CAUSE_DRAINED\x10\aB0Z.github.com/idyl-labs/hyperplane-go/wire/dockv3b\x06proto3"

var (
	file_idyl_dock_v3_dock_proto_rawDescOnce sync.Once
	file_idyl_dock_v3_dock_proto_rawDescData []byte
)

func file_idyl_dock_v3_dock_proto_rawDescGZIP() []byte {
	file_idyl_dock_v3_dock_proto_rawDescOnce.Do(func() {
		file_idyl_dock_v3_dock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idyl_dock_v3_dock_proto_rawDesc), len(file_idyl_dock_v3_dock_proto_rawDesc)))
	})
	return file_idyl_dock_v3_dock_proto_rawDescData
}

var file_idyl_dock_v3_dock_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_idyl_dock_v3_dock_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_idyl_dock_v3_dock_proto_goTypes = []any{
	(LaneCloseCause)(0),      // 0: idyl.dock.v3.LaneCloseCause
	(*DockHello)(nil),        // 1: idyl.dock.v3.DockHello
	(*DockWelcome)(nil),      // 2: idyl.dock.v3.DockWelcome
	(*DockDrain)(nil),        // 3: idyl.dock.v3.DockDrain
	(*DockOverloaded)(nil),   // 4: idyl.dock.v3.DockOverloaded
	(*LaneAttached)(nil),     // 5: idyl.dock.v3.LaneAttached
	(*LaneClosed)(nil),       // 6: idyl.dock.v3.LaneClosed
	(*ClientToEdge)(nil),     // 7: idyl.dock.v3.ClientToEdge
	(*EdgeToClient)(nil),     // 8: idyl.dock.v3.EdgeToClient
	(*commonv2.DockGen)(nil), // 9: idyl.membership.v2.DockGen
}
var file_idyl_dock_v3_dock_proto_depIdxs = []int32{
	9, // 0: idyl.dock.v3.DockHello.predecessor_gen:type_name -> idyl.membership.v2.DockGen
	9, // 1: idyl.dock.v3.DockWelcome.gen:type_name -> idyl.membership.v2.DockGen
	0, // 2: idyl.dock.v3.LaneClosed.cause:type_name -> idyl.dock.v3.LaneCloseCause
	1, // 3: idyl.dock.v3.ClientToEdge.hello:type_name -> idyl.dock.v3.DockHello
	2, // 4: idyl.dock.v3.EdgeToClient.welcome:type_name -> idyl.dock.v3.DockWelcome
	3, // 5: idyl.dock.v3.EdgeToClient.drain:type_name -> idyl.dock.v3.DockDrain
	4, // 6: idyl.dock.v3.EdgeToClient.overloaded:type_name -> idyl.dock.v3.DockOverloaded
	5, // 7: idyl.dock.v3.EdgeToClient.lane_attached:type_name -> idyl.dock.v3.LaneAttached
	6, // 8: idyl.dock.v3.EdgeToClient.lane_closed:type_name -> idyl.dock.v3.LaneClosed
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_idyl_dock_v3_dock_proto_init() }
func file_idyl_dock_v3_dock_proto_init() {
	if File_idyl_dock_v3_dock_proto != nil {
		return
	}
	file_idyl_dock_v3_dock_proto_msgTypes[6].OneofWrappers = []any{
		(*ClientToEdge_Hello)(nil),
	}
	file_idyl_dock_v3_dock_proto_msgTypes[7].OneofWrappers = []any{
		(*EdgeToClient_Welcome)(nil),
		(*EdgeToClient_Drain)(nil),
		(*EdgeToClient_Overloaded)(nil),
		(*EdgeToClient_LaneAttached)(nil),
		(*EdgeToClient_LaneClosed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idyl_dock_v3_dock_proto_rawDesc), len(file_idyl_dock_v3_dock_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idyl_dock_v3_dock_proto_goTypes,
		DependencyIndexes: file_idyl_dock_v3_dock_proto_depIdxs,
		EnumInfos:         file_idyl_dock_v3_dock_proto_enumTypes,
		MessageInfos:      file_idyl_dock_v3_dock_proto_msgTypes,
	}.Build()
	File_idyl_dock_v3_dock_proto = out.File
	file_idyl_dock_v3_dock_proto_goTypes = nil
	file_idyl_dock_v3_dock_proto_depIdxs = nil
}
