// Copyright 2026 Idyl Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: idyl/minting/v2/minting.proto

// This file defines the requests and replies for minting a Pod or session
// credential. A successful mint is atomic: it always returns the X.509-SVID
// chain together with its exact admission lease envelope and the trust
// snapshot the leaf verifies under, so a certificate without its lease
// cannot be represented. A Pod generation also carries the renewal instant
// the issuer selected.

package mintingv2

import (
	commonv2 "github.com/idyl-labs/hyperplane-go/wire/commonv2"
	trustv1 "github.com/idyl-labs/hyperplane-go/wire/trustv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MintPodSvidRequest asks for a credential generation for one Pod
// assignment. It names only the Pod and its assignment generation; every
// identity and placement fact in the resulting lease is issuer-derived.
type MintPodSvidRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CsrDer               []byte                 `protobuf:"bytes,1,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	PodId                string                 `protobuf:"bytes,2,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	AssignmentGeneration int64                  `protobuf:"varint,3,opt,name=assignment_generation,json=assignmentGeneration,proto3" json:"assignment_generation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MintPodSvidRequest) Reset() {
	*x = MintPodSvidRequest{}
	mi := &file_idyl_minting_v2_minting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintPodSvidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintPodSvidRequest) ProtoMessage() {}

func (x *MintPodSvidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_minting_v2_minting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintPodSvidRequest.ProtoReflect.Descriptor instead.
func (*MintPodSvidRequest) Descriptor() ([]byte, []int) {
	return file_idyl_minting_v2_minting_proto_rawDescGZIP(), []int{0}
}

func (x *MintPodSvidRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

func (x *MintPodSvidRequest) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

func (x *MintPodSvidRequest) GetAssignmentGeneration() int64 {
	if x != nil {
		return x.AssignmentGeneration
	}
	return 0
}

// MintSessionSvidRequest asks for a credential for one leg of a workload
// session.
type MintSessionSvidRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Node, workload, account and Namespace facts are deliberately absent:
	// the issuer derives them from the Pod's current placement and signs them
	// into the resulting lease rather than accepting assertions from the
	// requester.
	CsrDer               []byte               `protobuf:"bytes,1,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	SessionId            string               `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionKind          commonv2.SessionKind `protobuf:"varint,3,opt,name=session_kind,json=sessionKind,proto3,enum=idyl.membership.v2.SessionKind" json:"session_kind,omitempty"`
	SessionLeg           commonv2.SessionLeg  `protobuf:"varint,4,opt,name=session_leg,json=sessionLeg,proto3,enum=idyl.membership.v2.SessionLeg" json:"session_leg,omitempty"`
	PodId                string               `protobuf:"bytes,5,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	AssignmentGeneration int64                `protobuf:"varint,6,opt,name=assignment_generation,json=assignmentGeneration,proto3" json:"assignment_generation,omitempty"`
	GrantId              string               `protobuf:"bytes,7,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"` // required only for proxy leg
	ExpiresAtUnixS       uint64               `protobuf:"varint,8,opt,name=expires_at_unix_s,json=expiresAtUnixS,proto3" json:"expires_at_unix_s,omitempty"`
	// The sequence number of a Micropod within the Pod, when the session
	// targets one; 0 when the session targets the Pod itself. A positive
	// value is at most 2^53-1 and is valid only for exec and shell sessions,
	// on either leg. The resulting lease and session principal carry the same
	// value. Like every other field, it is part of the request's canonical
	// encoding, so two requests that differ only in it are different
	// requests.
	MicropodSequence uint64 `protobuf:"varint,9,opt,name=micropod_sequence,json=micropodSequence,proto3" json:"micropod_sequence,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MintSessionSvidRequest) Reset() {
	*x = MintSessionSvidRequest{}
	mi := &file_idyl_minting_v2_minting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintSessionSvidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintSessionSvidRequest) ProtoMessage() {}

func (x *MintSessionSvidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_minting_v2_minting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintSessionSvidRequest.ProtoReflect.Descriptor instead.
func (*MintSessionSvidRequest) Descriptor() ([]byte, []int) {
	return file_idyl_minting_v2_minting_proto_rawDescGZIP(), []int{1}
}

func (x *MintSessionSvidRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

func (x *MintSessionSvidRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MintSessionSvidRequest) GetSessionKind() commonv2.SessionKind {
	if x != nil {
		return x.SessionKind
	}
	return commonv2.SessionKind(0)
}

func (x *MintSessionSvidRequest) GetSessionLeg() commonv2.SessionLeg {
	if x != nil {
		return x.SessionLeg
	}
	return commonv2.SessionLeg(0)
}

func (x *MintSessionSvidRequest) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

func (x *MintSessionSvidRequest) GetAssignmentGeneration() int64 {
	if x != nil {
		return x.AssignmentGeneration
	}
	return 0
}

func (x *MintSessionSvidRequest) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *MintSessionSvidRequest) GetExpiresAtUnixS() uint64 {
	if x != nil {
		return x.ExpiresAtUnixS
	}
	return 0
}

func (x *MintSessionSvidRequest) GetMicropodSequence() uint64 {
	if x != nil {
		return x.MicropodSequence
	}
	return 0
}

// PodCredentialGeneration is a successful Pod mint.
type PodCredentialGeneration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertDer       [][]byte               `protobuf:"bytes,1,rep,name=cert_der,json=certDer,proto3" json:"cert_der,omitempty"`                     // DER, leaf first
	LeaseEnvelope []byte                 `protobuf:"bytes,2,opt,name=lease_envelope,json=leaseEnvelope,proto3" json:"lease_envelope,omitempty"`   // exact canonical ZoneAdmissionLease bytes
	RenewAtUnixS  uint64                 `protobuf:"varint,3,opt,name=renew_at_unix_s,json=renewAtUnixS,proto3" json:"renew_at_unix_s,omitempty"` // issuer-selected, inside the signed interval
	// The exact trust snapshot, with purpose POD, paired with this leaf
	// generation. A consumer validates and atomically installs it before
	// adopting the leaf.
	TrustSnapshot *trustv1.TrustSnapshot `protobuf:"bytes,4,opt,name=trust_snapshot,json=trustSnapshot,proto3" json:"trust_snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodCredentialGeneration) Reset() {
	*x = PodCredentialGeneration{}
	mi := &file_idyl_minting_v2_minting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodCredentialGeneration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodCredentialGeneration) ProtoMessage() {}

func (x *PodCredentialGeneration) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_minting_v2_minting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodCredentialGeneration.ProtoReflect.Descriptor instead.
func (*PodCredentialGeneration) Descriptor() ([]byte, []int) {
	return file_idyl_minting_v2_minting_proto_rawDescGZIP(), []int{2}
}

func (x *PodCredentialGeneration) GetCertDer() [][]byte {
	if x != nil {
		return x.CertDer
	}
	return nil
}

func (x *PodCredentialGeneration) GetLeaseEnvelope() []byte {
	if x != nil {
		return x.LeaseEnvelope
	}
	return nil
}

func (x *PodCredentialGeneration) GetRenewAtUnixS() uint64 {
	if x != nil {
		return x.RenewAtUnixS
	}
	return 0
}

func (x *PodCredentialGeneration) GetTrustSnapshot() *trustv1.TrustSnapshot {
	if x != nil {
		return x.TrustSnapshot
	}
	return nil
}

// SessionCredentialGeneration is a successful session mint.
type SessionCredentialGeneration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertDer       [][]byte               `protobuf:"bytes,1,rep,name=cert_der,json=certDer,proto3" json:"cert_der,omitempty"`                   // DER, leaf first
	LeaseEnvelope []byte                 `protobuf:"bytes,2,opt,name=lease_envelope,json=leaseEnvelope,proto3" json:"lease_envelope,omitempty"` // exact canonical ZoneAdmissionLease bytes
	// Sessions never renew; there is deliberately no renewal field.
	// The exact trust snapshot, with purpose POD, paired with this session
	// leaf. The client and proxy legs each validate and atomically install it
	// before adopting the generation.
	TrustSnapshot *trustv1.TrustSnapshot `protobuf:"bytes,3,opt,name=trust_snapshot,json=trustSnapshot,proto3" json:"trust_snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCredentialGeneration) Reset() {
	*x = SessionCredentialGeneration{}
	mi := &file_idyl_minting_v2_minting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCredentialGeneration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCredentialGeneration) ProtoMessage() {}

func (x *SessionCredentialGeneration) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_minting_v2_minting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCredentialGeneration.ProtoReflect.Descriptor instead.
func (*SessionCredentialGeneration) Descriptor() ([]byte, []int) {
	return file_idyl_minting_v2_minting_proto_rawDescGZIP(), []int{3}
}

func (x *SessionCredentialGeneration) GetCertDer() [][]byte {
	if x != nil {
		return x.CertDer
	}
	return nil
}

func (x *SessionCredentialGeneration) GetLeaseEnvelope() []byte {
	if x != nil {
		return x.LeaseEnvelope
	}
	return nil
}

func (x *SessionCredentialGeneration) GetTrustSnapshot() *trustv1.TrustSnapshot {
	if x != nil {
		return x.TrustSnapshot
	}
	return nil
}

// Refusal is a mint the issuer declined. code is a short machine-readable
// reason made of lowercase letters and hyphens.
type Refusal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Refusal) Reset() {
	*x = Refusal{}
	mi := &file_idyl_minting_v2_minting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refusal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refusal) ProtoMessage() {}

func (x *Refusal) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_minting_v2_minting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refusal.ProtoReflect.Descriptor instead.
func (*Refusal) Descriptor() ([]byte, []int) {
	return file_idyl_minting_v2_minting_proto_rawDescGZIP(), []int{4}
}

func (x *Refusal) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// MintPodSvidReply carries exactly one verdict for a MintPodSvidRequest.
type MintPodSvidReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Verdict:
	//
	//	*MintPodSvidReply_Generation
	//	*MintPodSvidReply_Refusal
	Verdict       isMintPodSvidReply_Verdict `protobuf_oneof:"verdict"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintPodSvidReply) Reset() {
	*x = MintPodSvidReply{}
	mi := &file_idyl_minting_v2_minting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintPodSvidReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintPodSvidReply) ProtoMessage() {}

func (x *MintPodSvidReply) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_minting_v2_minting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintPodSvidReply.ProtoReflect.Descriptor instead.
func (*MintPodSvidReply) Descriptor() ([]byte, []int) {
	return file_idyl_minting_v2_minting_proto_rawDescGZIP(), []int{5}
}

func (x *MintPodSvidReply) GetVerdict() isMintPodSvidReply_Verdict {
	if x != nil {
		return x.Verdict
	}
	return nil
}

func (x *MintPodSvidReply) GetGeneration() *PodCredentialGeneration {
	if x != nil {
		if x, ok := x.Verdict.(*MintPodSvidReply_Generation); ok {
			return x.Generation
		}
	}
	return nil
}

func (x *MintPodSvidReply) GetRefusal() *Refusal {
	if x != nil {
		if x, ok := x.Verdict.(*MintPodSvidReply_Refusal); ok {
			return x.Refusal
		}
	}
	return nil
}

type isMintPodSvidReply_Verdict interface {
	isMintPodSvidReply_Verdict()
}

type MintPodSvidReply_Generation struct {
	Generation *PodCredentialGeneration `protobuf:"bytes,1,opt,name=generation,proto3,oneof"`
}

type MintPodSvidReply_Refusal struct {
	Refusal *Refusal `protobuf:"bytes,2,opt,name=refusal,proto3,oneof"`
}

func (*MintPodSvidReply_Generation) isMintPodSvidReply_Verdict() {}

func (*MintPodSvidReply_Refusal) isMintPodSvidReply_Verdict() {}

// MintSessionSvidReply carries exactly one verdict for a
// MintSessionSvidRequest.
type MintSessionSvidReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Verdict:
	//
	//	*MintSessionSvidReply_Generation
	//	*MintSessionSvidReply_Refusal
	Verdict       isMintSessionSvidReply_Verdict `protobuf_oneof:"verdict"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintSessionSvidReply) Reset() {
	*x = MintSessionSvidReply{}
	mi := &file_idyl_minting_v2_minting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintSessionSvidReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintSessionSvidReply) ProtoMessage() {}

func (x *MintSessionSvidReply) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_minting_v2_minting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintSessionSvidReply.ProtoReflect.Descriptor instead.
func (*MintSessionSvidReply) Descriptor() ([]byte, []int) {
	return file_idyl_minting_v2_minting_proto_rawDescGZIP(), []int{6}
}

func (x *MintSessionSvidReply) GetVerdict() isMintSessionSvidReply_Verdict {
	if x != nil {
		return x.Verdict
	}
	return nil
}

func (x *MintSessionSvidReply) GetGeneration() *SessionCredentialGeneration {
	if x != nil {
		if x, ok := x.Verdict.(*MintSessionSvidReply_Generation); ok {
			return x.Generation
		}
	}
	return nil
}

func (x *MintSessionSvidReply) GetRefusal() *Refusal {
	if x != nil {
		if x, ok := x.Verdict.(*MintSessionSvidReply_Refusal); ok {
			return x.Refusal
		}
	}
	return nil
}

type isMintSessionSvidReply_Verdict interface {
	isMintSessionSvidReply_Verdict()
}

type MintSessionSvidReply_Generation struct {
	Generation *SessionCredentialGeneration `protobuf:"bytes,1,opt,name=generation,proto3,oneof"`
}

type MintSessionSvidReply_Refusal struct {
	Refusal *Refusal `protobuf:"bytes,2,opt,name=refusal,proto3,oneof"`
}

func (*MintSessionSvidReply_Generation) isMintSessionSvidReply_Verdict() {}

func (*MintSessionSvidReply_Refusal) isMintSessionSvidReply_Verdict() {}

var File_idyl_minting_v2_minting_proto protoreflect.FileDescriptor

const file_idyl_minting_v2_minting_proto_rawDesc = "" +
	"\n" +
	"\x1didyl/minting/v2/minting.proto\x12\x0fidyl.minting.v2\x1a\x1fidyl/membership/v2/common.proto\x1a\x19idyl/trust/v1/trust.proto\"y\n" +
	"\x12MintPodSvidRequest\x12\x17\n" +
	"\acsr_der\x18\x01 \x01(\fR\x06csrDer\x12\x15\n" +
	"\x06pod_id\x18\x02 \x01(\tR\x05podId\x123\n" +
	"\x15assignment_generation\x18\x03 \x01(\x03R\x14assignmentGeneration\"\x94\x03\n" +
	"\x16MintSessionSvidRequest\x12\x17\n" +
	"\acsr_der\x18\x01 \x01(\fR\x06csrDer\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12B\n" +
	"\fsession_kind\x18\x03 \x01(\x0e2\x1f.idyl.membership.v2.SessionKindR\vsessionKind\x12?\n" +
	"\vsession_leg\x18\x04 \x01(\x0e2\x1e.idyl.membership.v2.SessionLegR\n" +
	"sessionLeg\x12\x15\n" +
	"\x06pod_id\x18\x05 \x01(\tR\x05podId\x123\n" +
	"\x15assignment_generation\x18\x06 \x01(\x03R\x14assignmentGeneration\x12\x19\n" +
	"\bgrant_id\x18\a \x01(\tR\agrantId\x12)\n" +
	"\x11expires_at_unix_s\x18\b \x01(\x04R\x0eexpiresAtUnixS\x12+\n" +
	"\x11micropod_sequence\x18\t \x01(\x04R\x10micropodSequence\"\xc7\x01\n" +
	"\x17PodCredentialGeneration\x12\x19\n" +
	"\bcert_der\x18\x01 \x03(\fR\acertDer\x12%\n" +
	"\x0elease_envelope\x18\x02 \x01(\fR\rleaseEnvelope\x12%\n" +
	"\x0frenew_at_unix_s\x18\x03 \x01(\x04R\frenewAtUnixS\x12C\n" +
	"\x0etrust_snapshot\x18\x04 \x01(\v2\x1c.idyl.trust.v1.TrustSnapshotR\rtrustSnapshot\"\xa4\x01\n" +
	"\x1bSessionCredentialGeneration\x12\x19\n" +
	"\bcert_der\x18\x01 \x03(\fR\acertDer\x12%\n" +
	"\x0elease_envelope\x18\x02 \x01(\fR\rleaseEnvelope\x12C\n" +
	"\x0etrust_snapshot\x18\x03 \x01(\v2\x1c.idyl.trust.v1.TrustSnapshotR\rtrustSnapshot\"\x1d\n" +
	"\aRefusal\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x9f\x01\n" +
	"\x10MintPodSvidReply\x12J\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2(.idyl.minting.v2.PodCredentialGenerationH\x00R\n" +
	"generation\x124\n" +
	"\arefusal\x18\x02 \x01(\v2\x18.idyl.minting.v2.RefusalH\x00R\arefusalB\t\n" +
	"\averdict\"\xa7\x01\n" +
	"\x14MintSessionSvidReply\x12N\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2,.idyl.minting.v2.SessionCredentialGenerationH\x00R\n" +
	"generation\x124\n" +
	"\arefusal\x18\x02 \x01(\v2\x18.idyl.minting.v2.RefusalH\x00R\arefusalB\t\n" +
	"\averdictB3Z1github.com/idyl-labs/hyperplane-go/wire/mintingv2b\x06proto3"

var (
	file_idyl_minting_v2_minting_proto_rawDescOnce sync.Once
	file_idyl_minting_v2_minting_proto_rawDescData []byte
)

func file_idyl_minting_v2_minting_proto_rawDescGZIP() []byte {
	file_idyl_minting_v2_minting_proto_rawDescOnce.Do(func() {
		file_idyl_minting_v2_minting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idyl_minting_v2_minting_proto_rawDesc), len(file_idyl_minting_v2_minting_proto_rawDesc)))
	})
	return file_idyl_minting_v2_minting_proto_rawDescData
}

var file_idyl_minting_v2_minting_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_idyl_minting_v2_minting_proto_goTypes = []any{
	(*MintPodSvidRequest)(nil),          // 0: idyl.minting.v2.MintPodSvidRequest
	(*MintSessionSvidRequest)(nil),      // 1: idyl.minting.v2.MintSessionSvidRequest
	(*PodCredentialGeneration)(nil),     // 2: idyl.minting.v2.PodCredentialGeneration
	(*SessionCredentialGeneration)(nil), // 3: idyl.minting.v2.SessionCredentialGeneration
	(*Refusal)(nil),                     // 4: idyl.minting.v2.Refusal
	(*MintPodSvidReply)(nil),            // 5: idyl.minting.v2.MintPodSvidReply
	(*MintSessionSvidReply)(nil),        // 6: idyl.minting.v2.MintSessionSvidReply
	(commonv2.SessionKind)(0),           // 7: idyl.membership.v2.SessionKind
	(commonv2.SessionLeg)(0),            // 8: idyl.membership.v2.SessionLeg
	(*trustv1.TrustSnapshot)(nil),       // 9: idyl.trust.v1.TrustSnapshot
}
var file_idyl_minting_v2_minting_proto_depIdxs = []int32{
	7, // 0: idyl.minting.v2.MintSessionSvidRequest.session_kind:type_name -> idyl.membership.v2.SessionKind
	8, // 1: idyl.minting.v2.MintSessionSvidRequest.session_leg:type_name -> idyl.membership.v2.SessionLeg
	9, // 2: idyl.minting.v2.PodCredentialGeneration.trust_snapshot:type_name -> idyl.trust.v1.TrustSnapshot
	9, // 3: idyl.minting.v2.SessionCredentialGeneration.trust_snapshot:type_name -> idyl.trust.v1.TrustSnapshot
	2, // 4: idyl.minting.v2.MintPodSvidReply.generation:type_name -> idyl.minting.v2.PodCredentialGeneration
	4, // 5: idyl.minting.v2.MintPodSvidReply.refusal:type_name -> idyl.minting.v2.Refusal
	3, // 6: idyl.minting.v2.MintSessionSvidReply.generation:type_name -> idyl.minting.v2.SessionCredentialGeneration
	4, // 7: idyl.minting.v2.MintSessionSvidReply.refusal:type_name -> idyl.minting.v2.Refusal
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_idyl_minting_v2_minting_proto_init() }
func file_idyl_minting_v2_minting_proto_init() {
	if File_idyl_minting_v2_minting_proto != nil {
		return
	}
	file_idyl_minting_v2_minting_proto_msgTypes[5].OneofWrappers = []any{
		(*MintPodSvidReply_Generation)(nil),
		(*MintPodSvidReply_Refusal)(nil),
	}
	file_idyl_minting_v2_minting_proto_msgTypes[6].OneofWrappers = []any{
		(*MintSessionSvidReply_Generation)(nil),
		(*MintSessionSvidReply_Refusal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idyl_minting_v2_minting_proto_rawDesc), len(file_idyl_minting_v2_minting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idyl_minting_v2_minting_proto_goTypes,
		DependencyIndexes: file_idyl_minting_v2_minting_proto_depIdxs,
		MessageInfos:      file_idyl_minting_v2_minting_proto_msgTypes,
	}.Build()
	File_idyl_minting_v2_minting_proto = out.File
	file_idyl_minting_v2_minting_proto_goTypes = nil
	file_idyl_minting_v2_minting_proto_depIdxs = nil
}
