// Copyright 2026 Idyl Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: idyl/admission/v3/admission.proto

// This file defines zone-admission-lease/3, the contract under which
// dynamically admitted principals (Nodes, Pods, sessions and shares) dock.
// Such a principal presents one exact ZoneAdmissionLease together with a
// DockProofInput that binds the lease to its TLS connection (see the dock/3
// DockHello). The edge derives everything it knows about the principal from
// the authenticated SVID and the signed lease; admission needs no online
// lookup.
//
// Every Pod and session lease binds the workload identity to one account
// and one stable Namespace ID.
//
// Leases are signed by X.509-SVID admission signers. The lease signature is
// ECDSA P-256/SHA-256 in strict low-S DER, and the signer chain is a
// leaf-first X.509-SVID chain validated against the verifier's current local
// trust bundle. Each signature covers a domain-separated input: a fixed
// domain string, then the 4-byte big-endian length of the signed bytes, then
// the signed bytes. The lease domain is
// "idyl-zone-admission-lease-signature/v3\x00" and the dock proof domain is
// "idyl-dock-proof-signature/v1\x00".

package admissionv3

import (
	commonv2 "github.com/idyl-labs/hyperplane-go/wire/commonv2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeAdmission records the authority under which a Node was admitted. The
// only defined authority is provider capacity. The value is a signed
// issuance fact, never an assertion by the requester.
type NodeAdmission int32

const (
	NodeAdmission_NODE_ADMISSION_UNSPECIFIED NodeAdmission = 0
	NodeAdmission_NODE_ADMISSION_PROVIDER    NodeAdmission = 1
)

// Enum value maps for NodeAdmission.
var (
	NodeAdmission_name = map[int32]string{
		0: "NODE_ADMISSION_UNSPECIFIED",
		1: "NODE_ADMISSION_PROVIDER",
	}
	NodeAdmission_value = map[string]int32{
		"NODE_ADMISSION_UNSPECIFIED": 0,
		"NODE_ADMISSION_PROVIDER":    1,
	}
)

func (x NodeAdmission) Enum() *NodeAdmission {
	p := new(NodeAdmission)
	*p = x
	return p
}

func (x NodeAdmission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeAdmission) Descriptor() protoreflect.EnumDescriptor {
	return file_idyl_admission_v3_admission_proto_enumTypes[0].Descriptor()
}

func (NodeAdmission) Type() protoreflect.EnumType {
	return &file_idyl_admission_v3_admission_proto_enumTypes[0]
}

func (x NodeAdmission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeAdmission.Descriptor instead.
func (NodeAdmission) EnumDescriptor() ([]byte, []int) {
	return file_idyl_admission_v3_admission_proto_rawDescGZIP(), []int{0}
}

// ZoneAdmissionLease is the signed envelope, transmitted byte for byte. The
// signature covers payload exactly as received, never a decoded and
// re-encoded form. signer_key_id is SHA-256 over the signer leaf's SPKI. The
// signer chain is leaf first and omits the verifier's trust anchors.
type ZoneAdmissionLease struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Contract        string                 `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`                                        // "zone-admission-lease/3"
	Payload         []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                                          // canonical ZoneAdmissionLeasePayload bytes
	Signature       []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                                      // ECDSA P-256/SHA-256, strict low-S DER, bounded size
	SignerKeyId     []byte                 `protobuf:"bytes,4,opt,name=signer_key_id,json=signerKeyId,proto3" json:"signer_key_id,omitempty"`             // SHA-256, 32 bytes
	SignerCertChain [][]byte               `protobuf:"bytes,5,rep,name=signer_cert_chain,json=signerCertChain,proto3" json:"signer_cert_chain,omitempty"` // DER, X.509-SVID signer leaf first
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ZoneAdmissionLease) Reset() {
	*x = ZoneAdmissionLease{}
	mi := &file_idyl_admission_v3_admission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneAdmissionLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneAdmissionLease) ProtoMessage() {}

func (x *ZoneAdmissionLease) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_admission_v3_admission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneAdmissionLease.ProtoReflect.Descriptor instead.
func (*ZoneAdmissionLease) Descriptor() ([]byte, []int) {
	return file_idyl_admission_v3_admission_proto_rawDescGZIP(), []int{0}
}

func (x *ZoneAdmissionLease) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *ZoneAdmissionLease) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ZoneAdmissionLease) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ZoneAdmissionLease) GetSignerKeyId() []byte {
	if x != nil {
		return x.SignerKeyId
	}
	return nil
}

func (x *ZoneAdmissionLease) GetSignerCertChain() [][]byte {
	if x != nil {
		return x.SignerCertChain
	}
	return nil
}

// ZoneAdmissionLeasePayload is the canonical authorization payload. Presence
// is strict by endpoint kind; fields not admitted by that kind must be absent.
// All identity and placement facts are issuer-derived.
type ZoneAdmissionLeasePayload struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Version     uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`               // exactly 3; any other version is refused
	LeaseId     []byte                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"` // 16 opaque issuer bytes; audit only
	Zone        string                 `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	FabricPlane commonv2.Plane         `protobuf:"varint,4,opt,name=fabric_plane,json=fabricPlane,proto3,enum=idyl.common.v2.Plane" json:"fabric_plane,omitempty"`
	// Exact authenticated connection SVID URI. Node, pod, session and share
	// principals all use the zone SPIFFE trust domain.
	Principal         string                `protobuf:"bytes,5,opt,name=principal,proto3" json:"principal,omitempty"`
	SubjectSpkiSha256 []byte                `protobuf:"bytes,6,opt,name=subject_spki_sha256,json=subjectSpkiSha256,proto3" json:"subject_spki_sha256,omitempty"`
	EndpointKind      commonv2.EndpointKind `protobuf:"varint,7,opt,name=endpoint_kind,json=endpointKind,proto3,enum=idyl.common.v2.EndpointKind" json:"endpoint_kind,omitempty"`
	SubnetId          string                `protobuf:"bytes,8,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	OwnerScope        string                `protobuf:"bytes,9,opt,name=owner_scope,json=ownerScope,proto3" json:"owner_scope,omitempty"`
	AccountId         string                `protobuf:"bytes,10,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Pod and session leases: the stable Namespace UUID. It must equal the
	// namespace segment of the authenticated principal. Node and share leases
	// leave it empty.
	NamespaceId string `protobuf:"bytes,11,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	WorkloadId  string `protobuf:"bytes,12,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	NodeId      string `protobuf:"bytes,13,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PodId       string `protobuf:"bytes,14,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	// Pod leases use {pod_id}:{assignment_generation}; session leases use
	// {pod_id}.{assignment_generation} to match the canonical session URI.
	PodInstanceId        string               `protobuf:"bytes,15,opt,name=pod_instance_id,json=podInstanceId,proto3" json:"pod_instance_id,omitempty"`
	AssignmentGeneration uint64               `protobuf:"varint,16,opt,name=assignment_generation,json=assignmentGeneration,proto3" json:"assignment_generation,omitempty"`
	SessionId            string               `protobuf:"bytes,17,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionKind          commonv2.SessionKind `protobuf:"varint,18,opt,name=session_kind,json=sessionKind,proto3,enum=idyl.common.v2.SessionKind" json:"session_kind,omitempty"`
	SessionLeg           commonv2.SessionLeg  `protobuf:"varint,19,opt,name=session_leg,json=sessionLeg,proto3,enum=idyl.common.v2.SessionLeg" json:"session_leg,omitempty"`
	GrantId              string               `protobuf:"bytes,20,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"` // proxy leg only; client leg has no proxy grant
	// Adapter classes the endpoint may serve, as a bitset: 0 control dock,
	// 1 rpc, 2 stream, 3 flow, 4 ingress target, 5 splice, 6 federation. It
	// must be non-zero and use only those bits.
	AdapterClasses uint64 `protobuf:"varint,21,opt,name=adapter_classes,json=adapterClasses,proto3" json:"adapter_classes,omitempty"`
	// The largest set of lane classes a lane to this endpoint may be granted.
	// It uses the lane-class bits (2 stream, 3 flow, 4 ingress target, 5
	// splice leg) and must be a subset of adapter_classes.
	LaneClassCeiling     uint64        `protobuf:"varint,22,opt,name=lane_class_ceiling,json=laneClassCeiling,proto3" json:"lane_class_ceiling,omitempty"`
	PolicyProfile        string        `protobuf:"bytes,23,opt,name=policy_profile,json=policyProfile,proto3" json:"policy_profile,omitempty"` // bounded generic profile, never a resource id
	PolicyProfileVersion uint32        `protobuf:"varint,24,opt,name=policy_profile_version,json=policyProfileVersion,proto3" json:"policy_profile_version,omitempty"`
	NotBeforeUnixS       uint64        `protobuf:"varint,25,opt,name=not_before_unix_s,json=notBeforeUnixS,proto3" json:"not_before_unix_s,omitempty"`
	NotAfterUnixS        uint64        `protobuf:"varint,26,opt,name=not_after_unix_s,json=notAfterUnixS,proto3" json:"not_after_unix_s,omitempty"`
	NodeAdmission        NodeAdmission `protobuf:"varint,27,opt,name=node_admission,json=nodeAdmission,proto3,enum=idyl.admission.v3.NodeAdmission" json:"node_admission,omitempty"` // node kind only
	IssuedAtUnixS        uint64        `protobuf:"varint,28,opt,name=issued_at_unix_s,json=issuedAtUnixS,proto3" json:"issued_at_unix_s,omitempty"`                                  // not_before + the fixed 60-second backdate
	// Share leases only: must equal the share segment of the authenticated
	// principal.
	ShareId       string `protobuf:"bytes,30,opt,name=share_id,json=shareId,proto3" json:"share_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneAdmissionLeasePayload) Reset() {
	*x = ZoneAdmissionLeasePayload{}
	mi := &file_idyl_admission_v3_admission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneAdmissionLeasePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneAdmissionLeasePayload) ProtoMessage() {}

func (x *ZoneAdmissionLeasePayload) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_admission_v3_admission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneAdmissionLeasePayload.ProtoReflect.Descriptor instead.
func (*ZoneAdmissionLeasePayload) Descriptor() ([]byte, []int) {
	return file_idyl_admission_v3_admission_proto_rawDescGZIP(), []int{1}
}

func (x *ZoneAdmissionLeasePayload) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ZoneAdmissionLeasePayload) GetLeaseId() []byte {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

func (x *ZoneAdmissionLeasePayload) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *ZoneAdmissionLeasePayload) GetFabricPlane() commonv2.Plane {
	if x != nil {
		return x.FabricPlane
	}
	return commonv2.Plane(0)
}

func (x *ZoneAdmissionLeasePayload) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *ZoneAdmissionLeasePayload) GetSubjectSpkiSha256() []byte {
	if x != nil {
		return x.SubjectSpkiSha256
	}
	return nil
}

func (x *ZoneAdmissionLeasePayload) GetEndpointKind() commonv2.EndpointKind {
	if x != nil {
		return x.EndpointKind
	}
	return commonv2.EndpointKind(0)
}

func (x *ZoneAdmissionLeasePayload) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

func (x *ZoneAdmissionLeasePayload) GetOwnerScope() string {
	if x != nil {
		return x.OwnerScope
	}
	return ""
}

func (x *ZoneAdmissionLeasePayload) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ZoneAdmissionLeasePayload) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ZoneAdmissionLeasePayload) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *ZoneAdmissionLeasePayload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ZoneAdmissionLeasePayload) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

func (x *ZoneAdmissionLeasePayload) GetPodInstanceId() string {
	if x != nil {
		return x.PodInstanceId
	}
	return ""
}

func (x *ZoneAdmissionLeasePayload) GetAssignmentGeneration() uint64 {
	if x != nil {
		return x.AssignmentGeneration
	}
	return 0
}

func (x *ZoneAdmissionLeasePayload) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ZoneAdmissionLeasePayload) GetSessionKind() commonv2.SessionKind {
	if x != nil {
		return x.SessionKind
	}
	return commonv2.SessionKind(0)
}

func (x *ZoneAdmissionLeasePayload) GetSessionLeg() commonv2.SessionLeg {
	if x != nil {
		return x.SessionLeg
	}
	return commonv2.SessionLeg(0)
}

func (x *ZoneAdmissionLeasePayload) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *ZoneAdmissionLeasePayload) GetAdapterClasses() uint64 {
	if x != nil {
		return x.AdapterClasses
	}
	return 0
}

func (x *ZoneAdmissionLeasePayload) GetLaneClassCeiling() uint64 {
	if x != nil {
		return x.LaneClassCeiling
	}
	return 0
}

func (x *ZoneAdmissionLeasePayload) GetPolicyProfile() string {
	if x != nil {
		return x.PolicyProfile
	}
	return ""
}

func (x *ZoneAdmissionLeasePayload) GetPolicyProfileVersion() uint32 {
	if x != nil {
		return x.PolicyProfileVersion
	}
	return 0
}

func (x *ZoneAdmissionLeasePayload) GetNotBeforeUnixS() uint64 {
	if x != nil {
		return x.NotBeforeUnixS
	}
	return 0
}

func (x *ZoneAdmissionLeasePayload) GetNotAfterUnixS() uint64 {
	if x != nil {
		return x.NotAfterUnixS
	}
	return 0
}

func (x *ZoneAdmissionLeasePayload) GetNodeAdmission() NodeAdmission {
	if x != nil {
		return x.NodeAdmission
	}
	return NodeAdmission_NODE_ADMISSION_UNSPECIFIED
}

func (x *ZoneAdmissionLeasePayload) GetIssuedAtUnixS() uint64 {
	if x != nil {
		return x.IssuedAtUnixS
	}
	return 0
}

func (x *ZoneAdmissionLeasePayload) GetShareId() string {
	if x != nil {
		return x.ShareId
	}
	return ""
}

// DockProofInput is the exact canonical byte sequence the endpoint signs
// with its SVID key. The proof signature domain is applied outside this
// message. The input repeats every fact of the dock opening except the proof
// itself, so a verifier compares raw canonical bytes and never reconstructs
// signed bytes. exporter_value binds the proof to one TLS connection: a proof
// replayed on any other connection fails.
type DockProofInput struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Version             uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                                                     // exactly 1
	DockContract        string                 `protobuf:"bytes,2,opt,name=dock_contract,json=dockContract,proto3" json:"dock_contract,omitempty"`                        // "dock/3"
	ExporterLabel       string                 `protobuf:"bytes,3,opt,name=exporter_label,json=exporterLabel,proto3" json:"exporter_label,omitempty"`                     // "EXPORTER-IDYL-DOCK-PROOF-v1"
	ExporterValue       []byte                 `protobuf:"bytes,4,opt,name=exporter_value,json=exporterValue,proto3" json:"exporter_value,omitempty"`                     // 32 bytes from this TLS connection
	LeaseEnvelopeSha256 []byte                 `protobuf:"bytes,5,opt,name=lease_envelope_sha256,json=leaseEnvelopeSha256,proto3" json:"lease_envelope_sha256,omitempty"` // digest of exact envelope bytes
	KeepaliveMs         uint32                 `protobuf:"varint,6,opt,name=keepalive_ms,json=keepaliveMs,proto3" json:"keepalive_ms,omitempty"`
	PredecessorGen      *commonv2.DockGen      `protobuf:"bytes,7,opt,name=predecessor_gen,json=predecessorGen,proto3" json:"predecessor_gen,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DockProofInput) Reset() {
	*x = DockProofInput{}
	mi := &file_idyl_admission_v3_admission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockProofInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockProofInput) ProtoMessage() {}

func (x *DockProofInput) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_admission_v3_admission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockProofInput.ProtoReflect.Descriptor instead.
func (*DockProofInput) Descriptor() ([]byte, []int) {
	return file_idyl_admission_v3_admission_proto_rawDescGZIP(), []int{2}
}

func (x *DockProofInput) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DockProofInput) GetDockContract() string {
	if x != nil {
		return x.DockContract
	}
	return ""
}

func (x *DockProofInput) GetExporterLabel() string {
	if x != nil {
		return x.ExporterLabel
	}
	return ""
}

func (x *DockProofInput) GetExporterValue() []byte {
	if x != nil {
		return x.ExporterValue
	}
	return nil
}

func (x *DockProofInput) GetLeaseEnvelopeSha256() []byte {
	if x != nil {
		return x.LeaseEnvelopeSha256
	}
	return nil
}

func (x *DockProofInput) GetKeepaliveMs() uint32 {
	if x != nil {
		return x.KeepaliveMs
	}
	return 0
}

func (x *DockProofInput) GetPredecessorGen() *commonv2.DockGen {
	if x != nil {
		return x.PredecessorGen
	}
	return nil
}

var File_idyl_admission_v3_admission_proto protoreflect.FileDescriptor

const file_idyl_admission_v3_admission_proto_rawDesc = "" +
	"\n" +
	"!idyl/admission/v3/admission.proto\x12\x11idyl.admission.v3\x1a\x1bidyl/common/v2/common.proto\x1a\x1aidyl/common/v2/plane.proto\"\xb8\x01\n" +
	"\x12ZoneAdmissionLease\x12\x1a\n" +
	"\bcontract\x18\x01 \x01(\tR\bcontract\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\"\n" +
	"\rsigner_key_id\x18\x04 \x01(\fR\vsignerKeyId\x12*\n" +
	"\x11signer_cert_chain\x18\x05 \x03(\fR\x0fsignerCertChain\"\xbf\t\n" +
	"\x19ZoneAdmissionLeasePayload\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\fR\aleaseId\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\x128\n" +
	"\ffabric_plane\x18\x04 \x01(\x0e2\x15.idyl.common.v2.PlaneR\vfabricPlane\x12\x1c\n" +
	"\tprincipal\x18\x05 \x01(\tR\tprincipal\x12.\n" +
	"\x13subject_spki_sha256\x18\x06 \x01(\fR\x11subjectSpkiSha256\x12A\n" +
	"\rendpoint_kind\x18\a \x01(\x0e2\x1c.idyl.common.v2.EndpointKindR\fendpointKind\x12\x1b\n" +
	"\tsubnet_id\x18\b \x01(\tR\bsubnetId\x12\x1f\n" +
	"\vowner_scope\x18\t \x01(\tR\n" +
	"ownerScope\x12\x1d\n" +
	"\n" +
	"account_id\x18\n" +
	" \x01(\tR\taccountId\x12!\n" +
	"\fnamespace_id\x18\v \x01(\tR\vnamespaceId\x12\x1f\n" +
	"\vworkload_id\x18\f \x01(\tR\n" +
	"workloadId\x12\x17\n" +
	"\anode_id\x18\r \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06pod_id\x18\x0e \x01(\tR\x05podId\x12&\n" +
	"\x0fpod_instance_id\x18\x0f \x01(\tR\rpodInstanceId\x123\n" +
	"\x15assignment_generation\x18\x10 \x01(\x04R\x14assignmentGeneration\x12\x1d\n" +
	"\n" +
	"session_id\x18\x11 \x01(\tR\tsessionId\x12>\n" +
	"\fsession_kind\x18\x12 \x01(\x0e2\x1b.idyl.common.v2.SessionKindR\vsessionKind\x12;\n" +
	"\vsession_leg\x18\x13 \x01(\x0e2\x1a.idyl.common.v2.SessionLegR\n" +
	"sessionLeg\x12\x19\n" +
	"\bgrant_id\x18\x14 \x01(\tR\agrantId\x12'\n" +
	"\x0fadapter_classes\x18\x15 \x01(\x04R\x0eadapterClasses\x12,\n" +
	"\x12lane_class_ceiling\x18\x16 \x01(\x04R\x10laneClassCeiling\x12%\n" +
	"\x0epolicy_profile\x18\x17 \x01(\tR\rpolicyProfile\x124\n" +
	"\x16policy_profile_version\x18\x18 \x01(\rR\x14policyProfileVersion\x12)\n" +
	"\x11not_before_unix_s\x18\x19 \x01(\x04R\x0enotBeforeUnixS\x12'\n" +
	"\x10not_after_unix_s\x18\x1a \x01(\x04R\rnotAfterUnixS\x12G\n" +
	"\x0enode_admission\x18\x1b \x01(\x0e2 .idyl.admission.v3.NodeAdmissionR\rnodeAdmission\x12'\n" +
	"\x10issued_at_unix_s\x18\x1c \x01(\x04R\rissuedAtUnixS\x12\x19\n" +
	"\bshare_id\x18\x1e \x01(\tR\ashareIdJ\x04\b\x1d\x10\x1eR\x0eworkload_scope\"\xb6\x02\n" +
	"\x0eDockProofInput\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12#\n" +
	"\rdock_contract\x18\x02 \x01(\tR\fdockContract\x12%\n" +
	"\x0eexporter_label\x18\x03 \x01(\tR\rexporterLabel\x12%\n" +
	"\x0eexporter_value\x18\x04 \x01(\fR\rexporterValue\x122\n" +
	"\x15lease_envelope_sha256\x18\x05 \x01(\fR\x13leaseEnvelopeSha256\x12!\n" +
	"\fkeepalive_ms\x18\x06 \x01(\rR\vkeepaliveMs\x12@\n" +
	"\x0fpredecessor_gen\x18\a \x01(\v2\x17.idyl.common.v2.DockGenR\x0epredecessorGen*L\n" +
	"\rNodeAdmission\x12\x1e\n" +
	"\x1aNODE_ADMISSION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17NODE_ADMISSION_PROVIDER\x10\x01B5Z3github.com/idyl-labs/hyperplane-go/wire/admissionv3b\x06proto3"

var (
	file_idyl_admission_v3_admission_proto_rawDescOnce sync.Once
	file_idyl_admission_v3_admission_proto_rawDescData []byte
)

func file_idyl_admission_v3_admission_proto_rawDescGZIP() []byte {
	file_idyl_admission_v3_admission_proto_rawDescOnce.Do(func() {
		file_idyl_admission_v3_admission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idyl_admission_v3_admission_proto_rawDesc), len(file_idyl_admission_v3_admission_proto_rawDesc)))
	})
	return file_idyl_admission_v3_admission_proto_rawDescData
}

var file_idyl_admission_v3_admission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_idyl_admission_v3_admission_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_idyl_admission_v3_admission_proto_goTypes = []any{
	(NodeAdmission)(0),                // 0: idyl.admission.v3.NodeAdmission
	(*ZoneAdmissionLease)(nil),        // 1: idyl.admission.v3.ZoneAdmissionLease
	(*ZoneAdmissionLeasePayload)(nil), // 2: idyl.admission.v3.ZoneAdmissionLeasePayload
	(*DockProofInput)(nil),            // 3: idyl.admission.v3.DockProofInput
	(commonv2.Plane)(0),               // 4: idyl.common.v2.Plane
	(commonv2.EndpointKind)(0),        // 5: idyl.common.v2.EndpointKind
	(commonv2.SessionKind)(0),         // 6: idyl.common.v2.SessionKind
	(commonv2.SessionLeg)(0),          // 7: idyl.common.v2.SessionLeg
	(*commonv2.DockGen)(nil),          // 8: idyl.common.v2.DockGen
}
var file_idyl_admission_v3_admission_proto_depIdxs = []int32{
	4, // 0: idyl.admission.v3.ZoneAdmissionLeasePayload.fabric_plane:type_name -> idyl.common.v2.Plane
	5, // 1: idyl.admission.v3.ZoneAdmissionLeasePayload.endpoint_kind:type_name -> idyl.common.v2.EndpointKind
	6, // 2: idyl.admission.v3.ZoneAdmissionLeasePayload.session_kind:type_name -> idyl.common.v2.SessionKind
	7, // 3: idyl.admission.v3.ZoneAdmissionLeasePayload.session_leg:type_name -> idyl.common.v2.SessionLeg
	0, // 4: idyl.admission.v3.ZoneAdmissionLeasePayload.node_admission:type_name -> idyl.admission.v3.NodeAdmission
	8, // 5: idyl.admission.v3.DockProofInput.predecessor_gen:type_name -> idyl.common.v2.DockGen
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_idyl_admission_v3_admission_proto_init() }
func file_idyl_admission_v3_admission_proto_init() {
	if File_idyl_admission_v3_admission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idyl_admission_v3_admission_proto_rawDesc), len(file_idyl_admission_v3_admission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idyl_admission_v3_admission_proto_goTypes,
		DependencyIndexes: file_idyl_admission_v3_admission_proto_depIdxs,
		EnumInfos:         file_idyl_admission_v3_admission_proto_enumTypes,
		MessageInfos:      file_idyl_admission_v3_admission_proto_msgTypes,
	}.Build()
	File_idyl_admission_v3_admission_proto = out.File
	file_idyl_admission_v3_admission_proto_goTypes = nil
	file_idyl_admission_v3_admission_proto_depIdxs = nil
}
