// Copyright 2026 Idyl Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: idyl/trust/v1/trust.proto

// This file defines the trust snapshot: a bounded, purpose-scoped set of
// public CA certificates (generations) that a consumer installs as its trust
// anchors for one zone. No private key material has a field here.
//
// The structured fields are the bounded cross-language view. The
// canonical_payload_json field carries the exact canonical JSON payload over
// which the SHA-256 digest is computed, so every implementation names one
// digest. Validators require the structured fields and the canonical JSON to
// agree byte for byte after canonicalization; there is no second digest over
// the protobuf encoding.

package trustv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Purpose names the trust domain a snapshot serves. A snapshot for one
// purpose never stands in for another. POD covers Pod and session SVIDs;
// JOIN covers the credentials used when a Node joins.
type Purpose int32

const (
	Purpose_PURPOSE_UNSPECIFIED Purpose = 0
	Purpose_PURPOSE_JOIN        Purpose = 1
	Purpose_PURPOSE_POD         Purpose = 2
)

// Enum value maps for Purpose.
var (
	Purpose_name = map[int32]string{
		0: "PURPOSE_UNSPECIFIED",
		1: "PURPOSE_JOIN",
		2: "PURPOSE_POD",
	}
	Purpose_value = map[string]int32{
		"PURPOSE_UNSPECIFIED": 0,
		"PURPOSE_JOIN":        1,
		"PURPOSE_POD":         2,
	}
)

func (x Purpose) Enum() *Purpose {
	p := new(Purpose)
	*p = x
	return p
}

func (x Purpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Purpose) Descriptor() protoreflect.EnumDescriptor {
	return file_idyl_trust_v1_trust_proto_enumTypes[0].Descriptor()
}

func (Purpose) Type() protoreflect.EnumType {
	return &file_idyl_trust_v1_trust_proto_enumTypes[0]
}

func (x Purpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Purpose.Descriptor instead.
func (Purpose) EnumDescriptor() ([]byte, []int) {
	return file_idyl_trust_v1_trust_proto_rawDescGZIP(), []int{0}
}

// GenerationState is the lifecycle state of one CA generation. A snapshot
// distributes only PUBLISHING, ACTIVE and RETIRING generations; RETIRED and
// REVOKED generations are never included, and a snapshot that contains one
// is malformed.
type GenerationState int32

const (
	GenerationState_GENERATION_STATE_UNSPECIFIED GenerationState = 0
	// Published so consumers trust it before any certificate is issued under
	// it.
	GenerationState_GENERATION_STATE_PUBLISHING GenerationState = 1
	// Issuing certificates.
	GenerationState_GENERATION_STATE_ACTIVE GenerationState = 2
	// Not issuing; still trusted while certificates issued under it remain
	// valid.
	GenerationState_GENERATION_STATE_RETIRING GenerationState = 3
	GenerationState_GENERATION_STATE_RETIRED  GenerationState = 4
	GenerationState_GENERATION_STATE_REVOKED  GenerationState = 5
)

// Enum value maps for GenerationState.
var (
	GenerationState_name = map[int32]string{
		0: "GENERATION_STATE_UNSPECIFIED",
		1: "GENERATION_STATE_PUBLISHING",
		2: "GENERATION_STATE_ACTIVE",
		3: "GENERATION_STATE_RETIRING",
		4: "GENERATION_STATE_RETIRED",
		5: "GENERATION_STATE_REVOKED",
	}
	GenerationState_value = map[string]int32{
		"GENERATION_STATE_UNSPECIFIED": 0,
		"GENERATION_STATE_PUBLISHING":  1,
		"GENERATION_STATE_ACTIVE":      2,
		"GENERATION_STATE_RETIRING":    3,
		"GENERATION_STATE_RETIRED":     4,
		"GENERATION_STATE_REVOKED":     5,
	}
)

func (x GenerationState) Enum() *GenerationState {
	p := new(GenerationState)
	*p = x
	return p
}

func (x GenerationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerationState) Descriptor() protoreflect.EnumDescriptor {
	return file_idyl_trust_v1_trust_proto_enumTypes[1].Descriptor()
}

func (GenerationState) Type() protoreflect.EnumType {
	return &file_idyl_trust_v1_trust_proto_enumTypes[1]
}

func (x GenerationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerationState.Descriptor instead.
func (GenerationState) EnumDescriptor() ([]byte, []int) {
	return file_idyl_trust_v1_trust_proto_rawDescGZIP(), []int{1}
}

// TrustGeneration is one CA certificate in a snapshot. The certificate is an
// Ed25519 signing CA; the advertised validity must equal the certificate's
// own, and sha256_fingerprint is SHA-256 over certificate_der.
type TrustGeneration struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GenerationId      string                 `protobuf:"bytes,1,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	CertificateDer    []byte                 `protobuf:"bytes,2,opt,name=certificate_der,json=certificateDer,proto3" json:"certificate_der,omitempty"`
	Sha256Fingerprint []byte                 `protobuf:"bytes,3,opt,name=sha256_fingerprint,json=sha256Fingerprint,proto3" json:"sha256_fingerprint,omitempty"`
	NotBeforeUnixS    int64                  `protobuf:"varint,4,opt,name=not_before_unix_s,json=notBeforeUnixS,proto3" json:"not_before_unix_s,omitempty"`
	NotAfterUnixS     int64                  `protobuf:"varint,5,opt,name=not_after_unix_s,json=notAfterUnixS,proto3" json:"not_after_unix_s,omitempty"`
	PublishedSequence uint64                 `protobuf:"varint,6,opt,name=published_sequence,json=publishedSequence,proto3" json:"published_sequence,omitempty"` // snapshot sequence that first published it
	State             GenerationState        `protobuf:"varint,7,opt,name=state,proto3,enum=idyl.trust.v1.GenerationState" json:"state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrustGeneration) Reset() {
	*x = TrustGeneration{}
	mi := &file_idyl_trust_v1_trust_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustGeneration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustGeneration) ProtoMessage() {}

func (x *TrustGeneration) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_trust_v1_trust_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustGeneration.ProtoReflect.Descriptor instead.
func (*TrustGeneration) Descriptor() ([]byte, []int) {
	return file_idyl_trust_v1_trust_proto_rawDescGZIP(), []int{0}
}

func (x *TrustGeneration) GetGenerationId() string {
	if x != nil {
		return x.GenerationId
	}
	return ""
}

func (x *TrustGeneration) GetCertificateDer() []byte {
	if x != nil {
		return x.CertificateDer
	}
	return nil
}

func (x *TrustGeneration) GetSha256Fingerprint() []byte {
	if x != nil {
		return x.Sha256Fingerprint
	}
	return nil
}

func (x *TrustGeneration) GetNotBeforeUnixS() int64 {
	if x != nil {
		return x.NotBeforeUnixS
	}
	return 0
}

func (x *TrustGeneration) GetNotAfterUnixS() int64 {
	if x != nil {
		return x.NotAfterUnixS
	}
	return 0
}

func (x *TrustGeneration) GetPublishedSequence() uint64 {
	if x != nil {
		return x.PublishedSequence
	}
	return 0
}

func (x *TrustGeneration) GetState() GenerationState {
	if x != nil {
		return x.State
	}
	return GenerationState_GENERATION_STATE_UNSPECIFIED
}

// TrustSnapshot is the complete trust set for one zone and purpose. sequence
// increases monotonically: a consumer refuses a lower sequence as a rollback,
// treats the same sequence with the same digest as an idempotent
// redelivery, and refuses the same sequence with a different digest as
// equivocation. A snapshot is valid from issued_at to valid_until (at most
// 24 hours) and never outlives any generation it contains. Generations are
// sorted by generation_id.
type TrustSnapshot struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Zone                 string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	Purpose              Purpose                `protobuf:"varint,2,opt,name=purpose,proto3,enum=idyl.trust.v1.Purpose" json:"purpose,omitempty"`
	Sequence             uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	IssuedAtUnixS        int64                  `protobuf:"varint,4,opt,name=issued_at_unix_s,json=issuedAtUnixS,proto3" json:"issued_at_unix_s,omitempty"`
	ValidUntilUnixS      int64                  `protobuf:"varint,5,opt,name=valid_until_unix_s,json=validUntilUnixS,proto3" json:"valid_until_unix_s,omitempty"`
	Generations          []*TrustGeneration     `protobuf:"bytes,6,rep,name=generations,proto3" json:"generations,omitempty"`
	CanonicalPayloadJson []byte                 `protobuf:"bytes,7,opt,name=canonical_payload_json,json=canonicalPayloadJson,proto3" json:"canonical_payload_json,omitempty"`
	Sha256Digest         []byte                 `protobuf:"bytes,8,opt,name=sha256_digest,json=sha256Digest,proto3" json:"sha256_digest,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TrustSnapshot) Reset() {
	*x = TrustSnapshot{}
	mi := &file_idyl_trust_v1_trust_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustSnapshot) ProtoMessage() {}

func (x *TrustSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_idyl_trust_v1_trust_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustSnapshot.ProtoReflect.Descriptor instead.
func (*TrustSnapshot) Descriptor() ([]byte, []int) {
	return file_idyl_trust_v1_trust_proto_rawDescGZIP(), []int{1}
}

func (x *TrustSnapshot) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *TrustSnapshot) GetPurpose() Purpose {
	if x != nil {
		return x.Purpose
	}
	return Purpose_PURPOSE_UNSPECIFIED
}

func (x *TrustSnapshot) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TrustSnapshot) GetIssuedAtUnixS() int64 {
	if x != nil {
		return x.IssuedAtUnixS
	}
	return 0
}

func (x *TrustSnapshot) GetValidUntilUnixS() int64 {
	if x != nil {
		return x.ValidUntilUnixS
	}
	return 0
}

func (x *TrustSnapshot) GetGenerations() []*TrustGeneration {
	if x != nil {
		return x.Generations
	}
	return nil
}

func (x *TrustSnapshot) GetCanonicalPayloadJson() []byte {
	if x != nil {
		return x.CanonicalPayloadJson
	}
	return nil
}

func (x *TrustSnapshot) GetSha256Digest() []byte {
	if x != nil {
		return x.Sha256Digest
	}
	return nil
}

var File_idyl_trust_v1_trust_proto protoreflect.FileDescriptor

const file_idyl_trust_v1_trust_proto_rawDesc = "" +
	"\n" +
	"\x19idyl/trust/v1/trust.proto\x12\ridyl.trust.v1\"\xc7\x02\n" +
	"\x0fTrustGeneration\x12#\n" +
	"\rgeneration_id\x18\x01 \x01(\tR\fgenerationId\x12'\n" +
	"\x0fcertificate_der\x18\x02 \x01(\fR\x0ecertificateDer\x12-\n" +
	"\x12sha256_fingerprint\x18\x03 \x01(\fR\x11sha256Fingerprint\x12)\n" +
	"\x11not_before_unix_s\x18\x04 \x01(\x03R\x0enotBeforeUnixS\x12'\n" +
	"\x10not_after_unix_s\x18\x05 \x01(\x03R\rnotAfterUnixS\x12-\n" +
	"\x12published_sequence\x18\x06 \x01(\x04R\x11publishedSequence\x124\n" +
	"\x05state\x18\a \x01(\x0e2\x1e.idyl.trust.v1.GenerationStateR\x05state\"\xe4\x02\n" +
	"\rTrustSnapshot\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x120\n" +
	"\apurpose\x18\x02 \x01(\x0e2\x16.idyl.trust.v1.PurposeR\apurpose\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12'\n" +
	"\x10issued_at_unix_s\x18\x04 \x01(\x03R\rissuedAtUnixS\x12+\n" +
	"\x12valid_until_unix_s\x18\x05 \x01(\x03R\x0fvalidUntilUnixS\x12@\n" +
	"\vgenerations\x18\x06 \x03(\v2\x1e.idyl.trust.v1.TrustGenerationR\vgenerations\x124\n" +
	"\x16canonical_payload_json\x18\a \x01(\fR\x14canonicalPayloadJson\x12#\n" +
	"\rsha256_digest\x18\b \x01(\fR\fsha256Digest*E\n" +
	"\aPurpose\x12\x17\n" +
	"\x13PURPOSE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPURPOSE_JOIN\x10\x01\x12\x0f\n" +
	"\vPURPOSE_POD\x10\x02*\xcc\x01\n" +
	"\x0fGenerationState\x12 \n" +
	"\x1cGENERATION_STATE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bGENERATION_STATE_PUBLISHING\x10\x01\x12\x1b\n" +
	"\x17GENERATION_STATE_ACTIVE\x10\x02\x12\x1d\n" +
	"\x19GENERATION_STATE_RETIRING\x10\x03\x12\x1c\n" +
	"\x18GENERATION_STATE_RETIRED\x10\x04\x12\x1c\n" +
	"\x18GENERATION_STATE_REVOKED\x10\x05B1Z/github.com/idyl-labs/hyperplane-go/wire/trustv1b\x06proto3"

var (
	file_idyl_trust_v1_trust_proto_rawDescOnce sync.Once
	file_idyl_trust_v1_trust_proto_rawDescData []byte
)

func file_idyl_trust_v1_trust_proto_rawDescGZIP() []byte {
	file_idyl_trust_v1_trust_proto_rawDescOnce.Do(func() {
		file_idyl_trust_v1_trust_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idyl_trust_v1_trust_proto_rawDesc), len(file_idyl_trust_v1_trust_proto_rawDesc)))
	})
	return file_idyl_trust_v1_trust_proto_rawDescData
}

var file_idyl_trust_v1_trust_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_idyl_trust_v1_trust_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_idyl_trust_v1_trust_proto_goTypes = []any{
	(Purpose)(0),            // 0: idyl.trust.v1.Purpose
	(GenerationState)(0),    // 1: idyl.trust.v1.GenerationState
	(*TrustGeneration)(nil), // 2: idyl.trust.v1.TrustGeneration
	(*TrustSnapshot)(nil),   // 3: idyl.trust.v1.TrustSnapshot
}
var file_idyl_trust_v1_trust_proto_depIdxs = []int32{
	1, // 0: idyl.trust.v1.TrustGeneration.state:type_name -> idyl.trust.v1.GenerationState
	0, // 1: idyl.trust.v1.TrustSnapshot.purpose:type_name -> idyl.trust.v1.Purpose
	2, // 2: idyl.trust.v1.TrustSnapshot.generations:type_name -> idyl.trust.v1.TrustGeneration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_idyl_trust_v1_trust_proto_init() }
func file_idyl_trust_v1_trust_proto_init() {
	if File_idyl_trust_v1_trust_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idyl_trust_v1_trust_proto_rawDesc), len(file_idyl_trust_v1_trust_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idyl_trust_v1_trust_proto_goTypes,
		DependencyIndexes: file_idyl_trust_v1_trust_proto_depIdxs,
		EnumInfos:         file_idyl_trust_v1_trust_proto_enumTypes,
		MessageInfos:      file_idyl_trust_v1_trust_proto_msgTypes,
	}.Build()
	File_idyl_trust_v1_trust_proto = out.File
	file_idyl_trust_v1_trust_proto_goTypes = nil
	file_idyl_trust_v1_trust_proto_depIdxs = nil
}
